### ISSUE TITLE
Warning: The row size is too big for FORMAT/PL at chr1:21660353, requires 2321364500 bytes, skipping.

### ISSUE THREAD

**Issue by raonyguimaraes** [samtools/bcftools#1013]
Hi there,

I'm trying to merge a few thousand VCFs and I'm getting this warning:

Warning: The row size is too big for FORMAT/PL at chr1:21660353, requires 2321364500 bytes, skipping.

I would like to know if there is a way to fix this issue or to better debug it.

**Comment by pd3** [comment]
This happens when there are too many alternate alleles. It is not possible to represent such rows in the BCF format because the signed integer limit is exceeded (bcftools internally convert VCFs to BCFs, as working with BCFs is much faster). In most cases you can safely ignore the warning unless you'll need to work with PLs for that particular record.

**Comment by raonyguimaraes** [comment]
Hi Peter,

Thank you for clarifying the issue!
