### ISSUE TITLE
Can't install bcftools without htslib 

### ISSUE THREAD

**Issue by dianalemos** [samtools/bcftools#1037]
I'm trying to install bcftools on my macos.  
When I run `make` I get the error `cram/cram_io.c:61:10: fatal error: 'lzma.h' file not found`

I found this issue #570 and run the option to install htslib without this dependency. However, when I try to install bcftools again (following the instructions in the same issue) I get exactly the same error `cram/cram_io.c:61:10: fatal error: 'lzma.h' file not found` 
My `lzma.h` is in: 

> /Users/pc/brew/include/lzma.h 
> /Users/pc/brew/Cellar/xz/5.2.4/include/lzma.h

I also tried, without success: 

> gcc -g -Wall -O2 -I. -I/Users/pc/brew/include -c -o cram/cram_io.o cram/cram_io.c

**Comment by pd3** [comment]
The location of lzma must be passed to the configure script or you should set compiler's environment variables CFLAGS and LDFLAGS manually so that it knows where to look for the lzma library. See if any of these will help:

https://github.com/samtools/bcftools/issues/790#issuecomment-473586553
https://github.com/samtools/bcftools/issues/793
http://samtools.github.io/bcftools/howtos/install.html

**Comment by jkbonfield** [comment]
Are you doing ./configure (with appropriate flags) first, or just typing "make"?

**Comment by dianalemos** [comment]
Thank you for the help. 
It seems I just needed to run `./configure --with-htslib=DIR` to specify my htslib directory. I was just running `./configure`
