### ISSUE TITLE
filter by major DP4

### ISSUE THREAD

**Issue by migrau** [samtools/bcftools#1064]
Hi, 
When using bcftools to obtain a consensus (`samtools mpileup -A -uf ref.file bam.file | bcftools call -mv -Oz -o vcf.file`, `cat ref.file | bcftools consensus vcf.file > consensus.file`) for some specific positions, it selects the ALT value instead the REF, even if the number of reads (DP4) are very clear. For example: 

```
KU962131.1	975	.	C	T	22.1499	.	DP=212;VDB=0.30597;SGB=-0.680642;RPB=0.306036;MQB=0.998347;MQSB=0.999621;BQB=0.986804;MQ0F=0;ICB=1;HOB=0.5;AC=1;AN=2;DP4=95,3,12,0;MQ=59	GT:PL	0/1:59,0,255

KU962131.1	1002	.	A	G	98	.	DP=169;VDB=0.477704;SGB=-0.680642;RPB=1;MQB=1;MQSB=1;BQB=0.997653;MQ0F=0;ICB=1;HOB=0.5;AC=1;AN=2;DP4=72,2,12,0;MQ=60	GT:PL	0/1:134,0,255
```
In these two cases, I expect to keep the REF in the consensus, but bcftools uses T and G respectively. There is any way to use `bcftools filter` for these cases? I'm looking for the majority consensus.

Thanks,

**Comment by pd3** [comment]
You seem to be using old version of the programs and an old workflow (`samtools mpileup` rather than `bcftools mpileup`), please check the current workflow http://samtools.github.io/bcftools/howtos/variant-calling.html and update to the latest version if possible as described here http://samtools.github.io/bcftools/howtos/install.html.

Having said that, it will probably not solve your issue. The program seems to be doing the correct thing, a heterozygous genotype is in these cases is more likely than a homozygous reference genotype. 

If you want to remove such sites by applying a hard threshold on the proportion of non-reference reads via DP4, you could stream through
````
bcftools view -i '(DP4[2]+DP4[3])/sum(DP4)>0.25'
````

**Comment by migrau** [comment]
Thanks pd3. 
`bcftools view -e` is what I was looking for. Finally using:

 `bcftools view -e '(DP4[2]+DP4[3])<DP4[0]+DP4[1]'` since I just want to include the majority values `DP4[0]+DP4[1])/sum(DP4)>0.5'` and `DP4[2]+DP4[3])/sum(DP4)>0.5'`

DP4 only contains the number of **valid** reads, right? not the ones flagged during the alignment (QUAL|DUP, etc.)

**Comment by pd3** [comment]
That's correct, as the header states, DP4 includes high-quality bases which pass the filters. I'll close the issue now as it is resolved.

**Comment by seven1112233** [comment]
Hi, 
as DP4 includes high-quality bases which pass the filters, I have a question, what is the value of "high-quality"?

**Comment by pd3** [comment]
There are mapping qualities, base qualities and BAQ which can cause that some reads / bases are skipped due to the `mpileup -Q` option.
