### ISSUE TITLE
Tab-delimited text file to vcf/bcf

### ISSUE THREAD

**Issue by s-usr** [samtools/bcftools#1076]
From issue samtools/bcftools#933

Make CHROM identifiers in the 23andme file and the ref.fa file the same | Remove "chr" from the ref.fa file. bcftools can then do the tab-to-vcf/bcf conversion. With -O, one can use the following arguments to output compressed BCF (b), uncompressed BCF (u), compressed VCF (z), uncompressed VCF (v).

> bcftools convert -c ID,CHROM,POS,AA --tsv2vcf 23andme.txt --fasta-ref GRCh37.23andme.fa -s mySample -Oz -o mySample.vcf.gz

The request is: If anyone has a link to the file 'GRCh37.23andme.fa', please share! Is it really a FASTA formatted file? I believe not; why is it designated so? I believe it has the same format as the '23andme.txt' file. Please advise!

Thanks.

**Comment by pd3** [comment]
I don't understand the question well. You seem to be referring to this comment https://github.com/samtools/bcftools/issues/933#issuecomment-447475822, but that already shows how the file `GRCh37.23andme.fa` was generated.

It is a fasta reference file, the same build your 23&Me coordinates uses. In case your reference uses a different chromosome naming convention (`chr1` as opposed to `1`), you may need to add or remove it so that your reference file matches your 23&Me text file with SNPs.

**Comment by s-usr** [comment]
From the posting, `GRCh37.23andme.fa` is essentially `GRCh37.p13.genome.fa` with 'chr' removed. It has then to be indexed using `samtools faidx ...` I googled `GRCh37.p13` and found [ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.25_GRCh37.p13](url), but I do not see any `GRCh37.p13.genome.fa.gz`.

**Comment by pd3** [comment]
People name the reference genomes in different ways, the underlying sequence is usually the same though. If it's the GRCh37 build, it can be downloaded from here ftp://ftp.ensembl.org/pub/grch37/current/fasta/homo_sapiens/dna/Homo_sapiens.GRCh37.dna.primary_assembly.fa.gz and GRCh38 here ftp://ftp.ensembl.org/pub/release-97/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz

**Comment by s-usr** [comment]
Wonderful, thank you very much for your kindness.
