### ISSUE TITLE
Error: The chromosome block 9 is not contiguous, consider running with -a?

### ISSUE THREAD

**Issue by vymao** [samtools/bcftools#1105]
Hi,

I keep getting the error `The chromosome block 9 is not contiguous, consider running with -a.` when I try and run `bcftools concat` on some vcfs generated by GATK's Mutect2. I tried sorting the vcfs with `vcf-tools` but it did not help. I'm not sure why this error is occuring, as I have ran the exact same procedure (it is all through a pipeline) on other datasets before. Do you have any suggestions? There aren't any other error messages so I'm not sure where else to go for help on this issue.

**Comment by pd3** [comment]
The program can either concatenate the input files as they are or interleave records in case they overlap. I think the error message is trying to say that coordinates in some of the VCFs overlap. Can you try `bcftools query -f '%CHROM\t%POS\n'` to check if that's the case? If so, using the `-a` option should help.

**Comment by pd3** [comment]
This seems resolved, please reopen if not.

**Comment by goeckeritz** [comment]
Hi Petr, 

I am also having this issue, and for both of the files I'm trying to combine, I pipe through sort. These are the commands I'm using:
FILE 1:
`bcftools mpileup --threads 12 -Oz -a FORMAT/AD -f ${REFERENCE} ${GENO}_sorted.bam | bcftools call --threads 12 -Oz -m -a GQ | bcftools +fill-tags -Oz --threads 12 -- -t FORMAT/VAF | bcftools view --threads 12 --with-header -Oz -M2 | bcftools filter --threads 12 -i "QUAL>50 & (DP4[0]+DP4[1]+DP4[2]+DP4[3])>12 & (DP4[0]+DP4[1]+DP4[2]+DP4[3])<30 & GQ>30 & ((FORMAT/VAF>0.2 & FORMAT/VAF<0.8) | FORMAT/VAF=0)" | bcftools view --threads 12 --with-header -i 'TYPE="snp"' | bcftools sort -m 190G -Oz > /cluster/home/cgoeckeritz/bwa_full/embryos/vcfs/${GENO}_ALT.vcf.gz`

FILE 2: 
`bcftools mpileup --threads 12 -Oz -a FORMAT/AD -f ${REFERENCE} ${GENO}_sorted.bam | bcftools call --threads 12 -Oz -m -a GQ | bcftools +fill-tags -Oz --threads 12 -- -t FORMAT/VAF | bcftools view --threads 12 --with-header -Oz -M2 | bcftools filter --threads 12 -i "QUAL>50 & (DP4[0]+DP4[1]+DP4[2]+DP4[3])>12 & (DP4[0]+DP4[1]+DP4[2]+DP4[3])<30" | bcftools view --threads 12 --with-header -i 'GT="RR"' | bcftools sort -m 190G -Oz > /cluster/home/cgoeckeritz/bwa_full/embryos/vcfs/${GENO}_REF.vcf.gz
`
I also made an index for each. 

Then, to merge the files, I ran:
`bcftools concat --threads 12 -Oz /cluster/home/cgoeckeritz/bwa_full/embryos/vcfs/${GENO}_ALT.vcf.gz /cluster/home/cgoeckeritz/bwa_full/embryos/vcfs/${GENO}_REF.vcf.gz > /cluster/home/cgoeckeritz/bwa_full/embryos/vcfs/${GENO}_MERGED.vcf.gz`


Doing the command `bcftools query -f '%CHROM\t%POS\n'` on the MERGED outputs every single variant in the file. Moreover, every line is unique, so I know there is at least no repeated locations, which is good... because that wouldn't make a ton of sense. 

Nonetheless, I am getting this contiguous error for the first chromosome. I can add the -a option, but I'm worried that will cause some issues if I were to then use gtcheck, which is later in my pipeline. Also, when I run the suggested `bcftools query` command, I get the error (or is it a warning?) `[W::bcf_sr_add_reader] No BGZF EOF marker; file <file> may be truncated`, and the index fails to be made. It suggests I use the -f option to write it anyway, but should I be concerned about this?

Any thoughts / comments on why I am getting these errors would be much appreciated - and thank you so much for your time!

Kindly,
Charity
