### ISSUE TITLE
Asking for solution for warning "Both INFO/DP and FORMAT/DP exist, which one do you want?"

### ISSUE THREAD

**Issue by genmaibutter** [samtools/bcftools#1128]
Hi,

I try to generate the vcf file from bam file by using bcftools mpileup.
I install bcftools with conda, it is version => 1.9

I start with the first script and **I got only GT:PL data.**
bcftools mpileup -Ou -f hg19.fasta sample1.bam sample2.bam sample3.bam | bcftools call -Ou -mv > merge.vcf

Then, I want to add DP and AD in the sample details for further analysis GT:AD:DP:PL
By type this script. 
bcftools mpileup -Ou -a 'FORMAT/AD,FORMAT/DP' -f hg19.fasta sample1.bam sample2.bam sample3.bam | bcftools call -Ou -mv > merge.vcf

Then, I got this error/warning. **"Both INFO/DP and FORMAT/DP exist, which one do you want?"**

Can you give me some suggestion? How should I fix this script.

Thanks,J

**Comment by pd3** [comment]
This is definitely strange, this branch of the code should not be triggered using the command you show at all. Any chance you could provide a small test case to reproduce the problem?

**Comment by KunathBJ** [comment]
I had the exact same issue. As soon as I ask FORMAT/DP I have that issue. 
INFO/DP is not even an mpileup option so I really don't understand that...
I'm using the same version.

**Comment by pd3** [comment]
I am unable to reproduce the problem, with version 1.9 or later.

In order to debug this, please upgrade to the latest version and if the problem persists, please provide the exact command you are you using together with a test case.

Using test files from the distribution, this works as expected:
```
./bcftools mpileup test/mpileup/indel-AD.1.bam -f test/mpileup/indel-AD.1.fa -a FORMAT/AD,FORMAT/DP -Ou |  ./bcftools call -Ou -mv -o /dev/null
```

**Comment by SoraiaB** [comment]
I had the same issue using version 1.9.

`bcftools mpileup -a 'FORMAT/DP,FORMAT/SP,FORMAT/AD,FORMAT/ADF,FORMAT/ADR,INFO/AD,INFO/ADR,INFO/ADF' --skip-indels -Ou -f /path_to_reference/ref_genome.fa --bam-list /path_to_list/bamfile_list.txt | bcftools call -Ou -mv | bcftools filter -s LowQual -e '%QUAL<20 || DP>100' > /path_to_out/out.vcf`

and then I realized that the problem was the filter option 'DP' that should be changed to 'FORMAT/DP':

``bcftools mpileup -a 'FORMAT/DP,FORMAT/SP,FORMAT/AD,FORMAT/ADF,FORMAT/ADR,INFO/AD,INFO/ADR,INFO/ADF' --skip-indels -Ou -f /path_to_reference/ref_genome.fa --bam-list /path_to_list/bamfile_list.txt | bcftools call -Ou -mv | bcftools filter -s LowQual -e '%QUAL<20 || FORMAT/DP>100' > /path_to_out/out.vcf``

That's the 'FORMAT/INFO DP' that bcftools was having issues with. After changing this, it went fine!

**Comment by pd3** [comment]
I modified the error message to make it more informative. Hopefully this will help.
