### ISSUE TITLE
"fasta sequence does not mach REF allele" + "overlaps with another variant, skipping..."

### ISSUE THREAD

**Issue by AlejandraPanzera** [samtools/bcftools#1155]
Hello everyone,

I have been looking to generate a consensus sequence. 

So I called variants:
bcftools mpileup -Ou -f referencegenome.fasta species1.bam | bcftools call -mv -Oz -o species1.vcf.gz

Normalized indels:
bcftools norm -f  referencegenome.fasta species1.vcf.gz -Ob -o species1.bcf

Filter adjacent indels:
bcftools filter --IndelGap 5 species1.bcf -Ob -o species1.flt-indels.bcf
bcftools index species1.flt-indels.bcf

And then called consensus:
cat referencegenome.fasta | bcftools consensus species1.flt-indels.bcf > species1_consensusSeq.fasta

I am getting this type of error with version 1.9: 
The site PGA_scaffold0__898_contigs__length_106305454:148570 overlaps with another variant, skipping...
The fasta sequence does not match the REF allele at PGA_scaffold0__898_contigs__length_106305454:237646:
   .vcf: [AG]
   .vcf: [A] <- (ALT)
   .fa:  [tG]GCATTGCCCATTTCTTAAGCATTCACCACATCC

And only this part of the error:
The site PGA_scaffold0__898_contigs__length_106305454:148570 overlaps with another variant, skipping...

with the newest version (1.10).

And I have no idea how to solve this. Any help would be highly appreciated!

**Comment by dlema82** [comment]
I am receiving the same error: The fasta sequence does not match the REF allele at KP202265.1_Panthera_pardus:269:
   .vcf: [T] <- (REF)
   .vcf: [C] <- (ALT)
   .fa:  [N]NNNTACGCGTACACGCGTA
I just installed the newest version. Here is my command:
bcftools consensus -a N -f Ppardus_mtgenome_li_etal_plateau.fa -o A34746_mtgenome.fa -s A34746 /array/dlema/mtgenome/mtgenome_variants.vcf.gz &

I was trying out the new --absent option (from issues #940  and #848 ) to incorporate Ns into my consensus fasta instead of the REF base where data is missing. I thought the error had something to do with that, there was no documentation on the new --absent option yet, so I thought I was doing something wrong in implementation, and had planned to ask about that. But now I see @AlejandraPanzera has the same error for consensus without using the -a option. Although @AlejandraPanzera is not receiving the error in the latest version, while I still am.
How can this error be resolved?

**Comment by pd3** [comment]
@AlejandraPanzera the 1.10 message is not an error but a warning. It tells you that there were two VCF records that overlap, therefore the program can't really say what is the real sequence and does the pragmatic choice of skipping the offending record that came second.

By the way, if this is not obvious from the messages, I welcome a suggestion how to make this more understandable. I did not expect there could be any confusion about this. 

@dlema82 This may be a bug. It would help if you could provide a small test case to reproduce and debug the problem.

**Comment by dlema82** [comment]
Thank you @pd3 
The zipfile here contains the fasta reference for the mitochondrial genome (Ppardus_mtgenome....fa), a .bam of the mapped reads for sample A34746 (generated from bwa mem | samtools view | samtools sort | adna-ldup | picard AddOrReplaceReadGroups using the same reference).
The .bcf generated using:
bcftools mpileup -Ob -o mtgenome_variants.bcf -f Ppardus_mtgenome_li_etal_plateau.fa A34746_mtgenome.mapped.bam A52028_mtgenome.mapped.bam A52039_mtgenome.mapped.bam A52045_mtgenome.mapped.bam A52047_mtgenome.mapped.bam A80613_mtgenome.mapped.bam A81302_mtgenome.mapped.bam A81845_mtgenome.mapped.bam A87236_mtgenome.mapped.bam A89842_mtgenome.mapped.bam A120285_mtgenome.mapped.bam A161733_mtgenome.mapped.bam A164151_mtgenome.mapped.bam A165112_mtgenome.mapped.bam A186944_mtgenome.mapped.bam A208770_mtgenome.mapped.bam A213648_mtgenome.mapped.bam A238222_mtgenome.mapped.bam F1444_mtgenome.mapped.bam F27279_mtgenome.mapped.bam F30779_mtgenome.mapped.bam F31530_mtgenome.mapped.bam F34590_mtgenome.mapped.bam F35257_mtgenome.mapped.bam F83654_mtgenome.mapped.bam F89917_mtgenome.mapped.bam --threads 8

which was followed by this to call the variants in vcf.gz:
bcftools call -vm -Oz -o mtgenome_variants.vcf.gz mtgenome_variants.bcf --threads 8
tabix -p vcf mtgenome_variants

In another somewhat related topic, I am wondering if I should have done the calling as haploid, as the mitochondrial genome is only maternal. I see in the manual that ploidy is assigned as --ploidy _ASSEMBLY[?]_ but I am confused what to replace "_ASSEMBLY[?]_" with. Is it appropriate to use an integer such as 1 to indicate haploid?

Anyway, for the consensus I used:
bcftools consensus -a N -f Ppardus_mtgenome_li_etal_plateau.fa -o A34746_mtgenome.fa -s A34746 /array/dlema/mtgenome/mtgenome_variants.vcf.gz &

Please let me know if this is adequate or if I can provide anything else
[A34746_mtgenome.mapped.zip](https://github.com/samtools/bcftools/files/4181891/A34746_mtgenome.mapped.zip)

**Comment by AlejandraPanzera** [comment]
Thanks for the reply @pd3.

I understand it is a warning rather than an error, because I do get a consensus output file.

But downstream, when I try to mask low coverage or zero coverage regions I get error because the length of my consensus does not match the length of reference genome.

Is there anyway around this problem.. ? I need my reference genome and consensus sequence to be the same length.

Thanks so much in advance!

Alejandra

**Comment by pd3** [comment]
Thank you fofr the testing data @dlema82. Can you provide also the original reference sequence? 
The VCF is not normalized by the way, please see the recommended usage here http://samtools.github.io/bcftools/howtos/consensus-sequence.html

**Comment by dlema82** [comment]
@pd3  Apologies, I see now I sent the wrong reference. I am adding the original reference here. The same reference used for mapping is used for consensus.
Also, apologies, I had overlooked that it needed to be normalized. Is this done with bcftools norm?
[Ppardus_mtgenome_li_etal_plateau.fa.zip](https://github.com/samtools/bcftools/files/4194143/Ppardus_mtgenome_li_etal_plateau.fa.zip)

**Comment by pd3** [comment]
Thank you. I don't know what to expect from the panthera pardus genome assembly in terms of quality, but the alignments are very very poor. It is no wonder that in some cases they give a conflicting evidence, I am afraid there is not much that can be done here.

Regarding the question about ploidy, you can get a list of predefined ploidies by running `bcftools call --ploidy ?`. Note that bcftools can model only haploid or diploid genomes, therefore mtDNA can violate this assumption. For calling in arbitrary ploidy, try freebayes. However, variant calling works on human/mouse mtDNA, so arguably the problem here is the quality of the genome assembly.

**Comment by dlema82** [comment]
@pd3 The DNA were extracted from museum archived historical tissue, so it is degraded quality, so we expect low coverage poor quality shotgun for this experiment. However, I have run consensus on these samples and they worked before in previous version, without the -a prompt. Because the data are poor quality, when I ran consensus on them, I was getting terrible reference bias in my haplotype network maps. This is why I wanted to use the -a option to see if it would help the issue, so I installed the latest version. That is when the error arrived.
I have just tried again without the -a prompt and it works. 
I created a new vcf containing only the more robust samples (removed poor quality) and normalized it with:
bcftools norm -f Ppardus_mtgenome_li_etal_plateau.fa mtgenome_variants_removed_bad.vcf.gz 
I am attaching the data here. Please I hope you will try again to see if this is a bug with -a that can be fixed.
For these I used sample A52028:
bcftools consensus -a N -f Ppardus_mtgenome_li_etal_plateau.fa -o A52028_mtgenome.fa -s A52028 mtgenome_variants_removed_bad.vcf.gz &
[mtgenome_variants_removed_bad.vcf.zip](https://github.com/samtools/bcftools/files/4208733/mtgenome_variants_removed_bad.vcf.zip)

**Comment by pd3** [comment]
This is now fixed, thanks for reporting the bug. Let me know if you encounter more problems and good luck with the analysis.

**Comment by dlema82** [comment]
Thank you so much!! Works now. I appreciate your help. Take care.
