### ISSUE TITLE
Problems with filtering on FORMAT fields

### ISSUE THREAD

**Issue by Asutu** [samtools/bcftools#1180]
Hi,

not sure if this is a bug, a feature request or if I'm just not understanding  correctly the behaviour of `filter` when applied on a per sample basis. Having a VCF that looks like this:

```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##reference=file://some/path/dummy.fas
##contig=<ID=chr1,length=235147>
##FORMAT=<ID=RO,Number=1,Type=Integer,Description="Reference allele observation count">
##FORMAT=<ID=AO,Number=R,Type=Integer,Description="Alternate allele observation count">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	S1	S2	S3
chr1	251	.	C	T	68	.	.	GT:AO:RO	0/0:0,0:35	0/1:13,0:4	0/1:13,0:14
```

I want to filter (by setting the genotype of failed samples to `./.`) any heterozygous sample for which the reference allele observation (`RO`) or the alternate allele observation count (`AO`) are below a certain value, but I can't make this work with `bcftools filter`. The command I'm using is:

```
bcftools filter -S . -e 'FORMAT/GT[:]="het" & (MAX(FORMAT/RO) < 10 | MAX(FORMAT/AO) < 10)' test.vcf | bcftools query -f '%CHROM %POS[\tGT=%GT AO=%AO RO=%RO]\n'
```

which generates the following result:

```
chr1 251	GT=0/0 AO=0,0 RO=35	GT=0/1 AO=13,0 RO=4	GT=0/1 AO=13,0 RO=14
```

However, I was expecting to obtain a filtered genotype for sample S2:

```
chr1 251	GT=0/0 AO=0,0 RO=35	GT=./. AO=13,0 RO=4	GT=0/1 AO=13,0 RO=14
```

Using 
```
$ bcftools --version
bcftools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.
License Expat: The MIT/Expat license
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

Thanks,
Pedro

**Comment by Asutu** [comment]
Hmm, I looks at though `bcftools` always returns false if `MAX` is applied to a field with a single value. Doing:

```
$ bcftools filter -S . -e 'FORMAT/GT[:]="het" & (FORMAT/RO < 10 | MAX(FORMAT/AO) < 10)' test.vcf | bcftools query -f '%CHROM %POS[\tGT=%GT AO=%AO RO=%RO]\n'
chr1 251	GT=0/0 AO=0,0 RO=35	GT=./. AO=13,0 RO=4	GT=0/1 AO=13,0 RO=14
```

seems to generate the expected output.

**Comment by pd3** [comment]
The problem is that the functions like MAX do not operate per sample but across all samples. 

Thinking about possible solutions, first I was thinking the functions could be made smarter and do the right think automatically depending on the context: if the tag has multiple values, one would write `MAX(AO)` to evaluate to the per-sample maximum AO values. Writing `MAX(MAX(AO))`  would then give the maximum of these.

Alternatively, there would be two functions that would be called explicitly, say MAX1 that evaluates to a single value (the way the current MAX does), and a new MAX that would evaluate to an array of per-sample maximum values.

The most difficult part here is to make the solution intuitive and, preferably, backwards compatible.  I am open to suggestions.

**Comment by Asutu** [comment]
Thanks for looking into this.
I ended up coding this particular case in python but having these functions (possibly with other names to keep backwards compatibility) to operate on a per sample basis would be a very positive addition to BCFtools.

**Comment by pd3** [comment]
This is now done, it should be possible to filter using `SMPL_MAX(FORMAT/AO)<10` now.
