### ISSUE TITLE
Why bcftools reheader don't support -Oz ? 

### ISSUE THREAD

**Issue by Shicheng-Guo** [samtools/bcftools#1181]
I am wondering why Why bcftools reheader don't support -Oz ? 

`bcftools reheader -s newname.txt final.rs.vcf.gz -o exome.rename.vcf.gz
`

Thank

Shicheng

**Comment by pd3** [comment]
Since it is designed to be ultra fast, it does not recode between formats and can do even without recompressing in some situations. You can pipe through `bcftools view` if you need that functionality. In the command you showing, both input and output is a compressed VCF, in your case the -Oz option is not needed anyway.
