### ISSUE TITLE
Modify variants definition to remove * from ALT alleles

### ISSUE THREAD

**Issue by fabiennejh** [samtools/bcftools#1195]
Good morning,

When you normalize a vcf file with bcftools norm, you can result in lines like this ones : 
chr1	111957547	.	GGGTCAGGGTCTTTTCCCCAGGGGTCACAGACTGATAACCCACAGA	G
chr1	111957547	.	G	* 

How can I use bcftools to  modify the second one in :
chr1	111957546	.	AG	A 

Thank you for your help

**Comment by pd3** [comment]
I don't understand the logic of the request, both are different things.

**Comment by fabiennejh** [comment]
Hello, 

If you prefer, I was wondering how using bcftools to remove * from ALT field of a vcf file. I was thinking that bcftools norm could do it, but it isn't the case. Is there another function of bcftools to do this ?

Thank you

**Comment by pd3** [comment]
Short answer, no, it is not possible. The meaning of the star allele is more subtle; it is used when a sequence deleted in one haplotype spans a variant site in another haplotype. The two cases (`POS=11  REF=G  ALT=*` vs `POS=10  REF=AG  ALT=A`) are not necessarily the same thing.

**Comment by jon4thin** [comment]
The `*` are introduced so that there is a reported "SNP" at a specific site that an INDEL is spanning ([INDEL overlapping a SNP](https://gatk.broadinstitute.org/hc/en-us/articles/360035531912-Spanning-or-overlapping-deletions-allele)) . Essentially, someone might want to know the "genotype" at a specific position, but it might be that ther is no SNP there, but there is an upstream deletion that spans that specific base. This allows someone to recover a "SNP" at positions that span an indel. The issue with this annotation is that it is not standard [IUPAC](https://www.bioinformatics.org/sms/iupac.html) annotation and triggers an error in many downstream applications. I think the question is, how can I removed the * and <NON_REF> annotations from an already created .g.vcf, before genotyping, and is there a way to remove these annotations from a genotyped vcf? Or is the only way to exclude this reporting style before creation of the g.vcfs?

**Comment by jon4thin** [comment]
The * are introduced so that there is a reported "SNP" at a specific site that an INDEL is spanning ([INDEL overlapping a SNP](https://gatk.broadinstitute.org/hc/en-us/articles/360035531912-Spanning-or-overlapping-deletions-allele)) . Essentially, someone might want to know the "genotype" at a specific position, but it might be that there is no SNP there, but there is an upstream deletion that spans that specific base. This allows someone to recover a "SNP" at positions that span an indel. The issue with this annotation is that it is not standard [IUPAC](https://www.bioinformatics.org/sms/iupac.html) annotation and triggers an error in many downstream applications. 

For @pd3 , I my question is how can I removed the * and <NON_REF> annotations from an already created .g.vcf, before genotyping, and is there a way to remove these annotations from a genotyped vcf? Or is the only way to exclude this reporting style before creation of the g.vcfs?

**Comment by jon4thin** [comment]
I opened a new question:
https://github.com/samtools/bcftools/issues/2258
