### ISSUE TITLE
Annotating .dose.vcf.gz files from Michigan server

### ISSUE THREAD

**Issue by rskl92** [samtools/bcftools#1261]
Hi,

I am trying to annotate (Convert the chr:pos) into rsid using the following code. However, I get the following error message "
Failed to open -: not compressed with bgzip" . Sorry if I've misunderstood but I thought it can take unzipped files too? These are files which I imputed and were directly downloaded from the Michigan server. Do I need to do something else before using them as input for bcftools? 
```
bcftools annotate \
    --output-type v \
    --remove ID \
    --set-id +'%CHROM:%POS:%REF:%ALT' \
    chr21.dose.vcf.gz \
| bcftools annotate \
    --annotations All_20170710.vcf.gz \
    --columns ID \
    --output-type v \
| plink \
    --vcf /dev/stdin \
    --keep-allele-order \
    --double-id \
    --make-bed
    --out chr21
```

Many thanks

**Comment by pd3** [comment]
Most commands that take two or more input files on input, such as `annotate` require both files compressed and indexed. You need to split your pipeline in two steps:
```
bcftools annotate --set-id ... -Ob tmp.bcf
bcftools index tmp.bcf

bcftools annotate --annotations All_20170710.vcf.gz .. tmp.bcf  | plink ...
```

By the way, when streaming from one bcftools command into another, it is better to use `-Ou` instead of `-Ov`; for large files with many samples this is makes a big difference in speed.
