### ISSUE TITLE
how does haploid calling work?

### ISSUE THREAD

**Issue by ahorvath** [samtools/bcftools#1339]
Dear Author,

I have WGS data from two really similar yeast populations where the sets of SNPs called should be almost identical.

If `--ploidy 1` is being set in one sample, I don't get the following mutation called:

```
I	10913	.	G	A	20.0499	.	_DP=9;VDB=0.27062;SGB=-0.556411;RPB=0.868321;MQB=0.992367;BQB=0.992367;MQ0F=0;AF1=0.499999;AC1=1;DP4=4,0,4,0;MQ=25;FQ=20.5146;PV4=1,1,1,1	GT:PL	0/1:50,0,51_
```

While I always get this called in the other sample, irrespective to the ploidy setting.

```
I	10913	.	G	A	48.0289	.	_DP=10;VDB=0.00794617;SGB=-0.636426;RPB=0.714286;MQB=1;BQB=0.857143;MQ0F=0;AF1=0.502513;AC1=1;DP4=2,0,7,0;MQ=25;FQ=-7.778;PV4=1,0.249747,1,1	GT:PL	0/1:78,0,20_
```

Can you tell me how exactly the filtering driven by `--ploidy 1` works?

Many thanks for the great software.

Best,
Attila

**Comment by pd3** [comment]
I changed the title as this is a question about haploid calling rather than filtering.

The calling framework is the same as described here http://samtools.github.io/bcftools/call-m.pdf, the difference is that only single-allele genotypes are considered. Obviously, the program must choose between 0 or 1, my guess is that the prior probability makes the alternate genotype less likely. This can be changed by increasing the prior (`call -P`) which is 1.1e-3 by default.
