### ISSUE TITLE
Bcftools filter seems incompatible with newer gnomad data

### ISSUE THREAD

**Issue by gbjerke** [samtools/bcftools#1387]
Hi,
Gnomad seems to have switched some of the population identifiers from an underscore to a hyphen (e.g. AF_afr to AF-afr) and this does not seem to work with bcftools, it seems to split on the hyphen:
bcftools query -f '%AF;%AF-afr\n' gnomad.genomes.v3.1.sites.chrY.vcf.bgz | head
Gives the output:
[E::bcf_hdr_parse_line] Could not parse the header line: "##VEP version: v101"
[E::bcf_hdr_parse_line] Could not parse the header line: "##dbSNP version: b154"
0;0-afr
0;0-afr
0;0-afr
0;0-afr
0;0-afr
0;0-afr
9.39585e-05;9.39585e-05-afr
0;0-afr
0;0-afr
0;0-afr

It seems to print the AF twice and then literally -afr after. Is there a fix for this or a work around? I have tried running the file through sed first to change each population back to an underscore, but that is very slow with files the size of gnomad.
Thank you very much!

**Comment by pd3** [comment]
This is a problem with gnomAD, not BCFtools. Hyphens are not allowed in tag names, see section 1.6.1 bullet point 8 of VCF specification http://samtools.github.io/hts-specs/VCFv4.3.pdf

Best would be to bring this to the attention of gnomAD people.

**Comment by jmarshall** [comment]
The situation is more complicated than that.

These gnomAD data files declare themselves as `##fileformat=VCFv4.2`, presumably because Picard/etc have only partial (reading only) support for VCF v4.3 (and prior to [htsjdk 2.20.0](https://github.com/samtools/htsjdk/releases/tag/2.20.0) the Java tools had no support for v4.3). [VCF v4.2](http://samtools.github.io/hts-specs/VCFv4.2.pdf) has no restrictions on the characters in INFO/FORMAT keys, and does not mention the upcoming restrictions in later VCF versions. So gnomAD have produced valid VCF v4.2 files — but unfortunately the keys used are incompatible with VCF v4.3.

BCFtools (quite reasonably) takes advantage of the INFO/FORMAT key charset restrictions in its implementation (in particular, as we see here, in its query syntax) without implementing special cases for earlier VCF versions. So it is also technically true that BCFtools is failing to process a valid VCF v4.2 file here.

So there are infelicities in all three — the specifications, gnomAD, and BCFtools — contributing to this problem. Ideally from BCFtools's point of view, gnomAD would change these keys to be compatible with the v4.3 rules (even if they still produce v4.2 files), but these files have been around [since October at least](https://gnomad.broadinstitute.org/blog/2020-10-gnomad-v3-1/) so that might cause some disruption. (Are the [3.0 files](https://gnomad.broadinstitute.org/blog/2019-10-gnomad-v3-0/) still available for download? What INFO keys did they use?)

(Thanks @gbjerke for bringing this to everyone's attention!)

**Comment by pd3** [comment]
The lack of explicit mention in v4.2 did not mean that the intention was to support dashes in tag names. Quite the opposite. The VCF was drafted with implicit assumptions and the language was made more clear later to prevent confusions like this. BCFtools is not going to back implement support for dashes in tag names.

@gbjerke As a quick solution, please try `bcftools annotate  --rename-annots` to use more sensible names.

**Comment by gbjerke** [comment]
@pd3 Thank you for the solution of using bcftools annotate --rename-annots, I'll try that!
