### ISSUE TITLE
bcftools call is detecting lots of REF reads that's not in the bam file (small test data set included)

### ISSUE THREAD

**Issue by danrlu** [samtools/bcftools#1446]
When using bcftools to call variants on a virus genome, position `28253` has `DP4=6,86,162,25` and `AD` of `92,187`, but the bam file in the browser shows very few (if any) REF reads. I tried fiddling with `--no-BAQ`, `--min-MQ` and `bcftools call -m -P` per previous discussions but didn't see much difference. 

Command: 
`bcftools mpileup -Q 20 -d 100000 -L 100000 -a AD,DP,SP --min-ireads 20 --gap-frac 0.5 --no-BAQ -f MN908947.3.fa small_test.bam | bcftools call --ploidy 1 -c - | bcftools view -c 1 -Ov > small_test_no_BAQ.vcf`

[Test data](https://github.com/danrlu/debug_data/tree/main/bcftools_indel) to reproduce results from the command above.

Version: bcftools 1.12 from Conda

Possib related issues: #1276 #1348 

Any suggestions would be appreciated, and thank you for such a useful tool!!!

**Comment by jkbonfield** [comment]
I need to look at this in detail in the code, but a quick experiment shows -Q20 vs -Q0 has a huge change:

```
-Q20   DP4=5,76,163,35
-Q0    DP4=3,1,165,110
```

This appears to be indicating that quality filtering isn't removing bases from the counts, but moving them from one class to another.  That sounds like a bug.  I'll do more research.  Thanks for the report and data.

**Comment by jkbonfield** [comment]
The origin on this is in 3c1205c1, which explicitly doesn't skip quals < `-Q` for indels (as it does for SNPs) and instead counts them as REF.  This was a deliberate change.  See the comment:

```
            // This read is not counted as indel. Instead of skipping it, treat it as ref. It is
            // still only an approximation, but gives more accurate AD counts and calls correctly
            // hets instead of alt-homs in some cases (see test/mpileup/indel-AD.1.sam)
            if ( q < bca->min_baseQ ) b = 0, q = (int)bam_get_qual(p->b)[p->qpos];
```

The code has had a major revamp (albeit in a draft PR and not merged), so I should evaluate whether reversing this is now appropriate.

@pd3 do you have any more insight or data showing why this change was made?  I see there is test/mpileup/indel-AD.1.sam, which I'll take a look at, but anything more would be useful (I can try some larger dataset evaluations).  On the face of it, it sounds like the fix is worse than the problem, but the accuracy of GT calling for indels is now (or will be) considerably more accurate than before anyway so maybe it's time to fix this too.
