### ISSUE TITLE
looking for position displays another position

### ISSUE THREAD

**Issue by aknfa** [samtools/bcftools#1449]
I splitted multiallelic and biallelic sites in my vcf files separately. I just picked a random position from multiallelic sites. Then I searched it in the files of all sites and biallelic sites, it displayed a different position. Can someone explain the reason?

**The position in the file of all sites**
```
zgrep "26710803" allsites.vcf.gz

10      26710803        .       ATTT    ATT,ATTTTT,ATTTT,AT,A,* 354571  PASS    AC=2706,17,56,284,1,0;AF=0.368,0.002432,0.007295,0.038,0.017,0.000256;AN=7352
10      26710819        .       A       T       128.44  VQSRTrancheSNP90.00to99.00      AC=10;AF=0.001245;AN=7532

```
**only in biallelic sites**

````
zgrep "26710803" biallelicsites.vcf.gz


10      26710819        .       A       T       128.44  VQSRTrancheSNP90.00to99.00      AC=10;AF=0.001245;AN=7532

````

**Comment by pd3** [comment]
I don't understand the question completely, you are showing only the use of the command `grep` but not what you do with `bcftools`. Shall I assume the problem is with `-r` pulling in overlapping records? This is actually a feature. One can combine `-r` with `-t` to exclude records outside the range.

For the most recent complaint about this see also #1420 and #1421.
