### ISSUE TITLE
FILTER 'STRANDBIAS' is not defined in the header

### ISSUE THREAD

**Issue by mantonglaw** [samtools/bcftools#1525]
Hello,
    I ran the command 
"bcftools view PDc_nofil_calmd.vcf -O b -o PDc_nofil_calmd.bcf.gz" 
and then there is an error suggestion
"[W::vcf_parse] FILTER 'STRANDBIAS' is not defined in the header
[E::bcf_write] Unchecked error (2), exiting
I don't know how to deal with the error, could you give me a hand please?
Thanks

**Comment by pd3** [comment]
The program complains because you are trying to create a BCF and the header does not contain definitions of all annotations contained in the body. Specifically, a line like this is missing:
```
##FILTER=<ID=STRANDBIAS,Description="some description">
```
In BCF all tags must be defined in the header because the BCF body only contains numeric ids of the annotations defined in the header.
