### ISSUE TITLE
bcftools csq: Why is there sometimes no consequence field if the sequence is annotated as protein coding?

### ISSUE THREAD

**Issue by MWendorff** [samtools/bcftools#1552]
Why is there sometimes no consequence field if the sequence is annotated as protein coding?

Here one example. See first entry:

5       139680769       5_139680769_CTCT_C      CTCT    C       1813    PASS    AF=5.1e-05;AQ=1813;ExcessHet=4.7712;QD=9.85;AC=1;AN=2;BCSQ=inframe_deletion|CXXC5|ENST00000503511|protein_coding|+,inframe_deletion|CXXC5|ENST00000509238|protein_coding|+|82YS>82Y|139680769CTCT>C,inframe_deletion|CXXC5|ENST00000504944|protein_coding|+|82YS>82Y|139680769CTCT>C,inframe_deletion|CXXC5|ENST00000520967|protein_coding|+|82YS>82Y|139680769CTCT>C,inframe_deletion|CXXC5|ENST00000504844|protein_coding|+|82YS>82Y|139680769CTCT>C,inframe_deletion|CXXC5|ENST00000502716|protein_coding|+|82YS>82Y|139680769CTCT>C,inframe_deletion|CXXC5|ENST00000511457|protein_coding|+|82YS>82Y|139680769CTCT>C,inframe_deletion|CXXC5|ENST00000511048|protein_coding|+|82YS>82Y|139680769CTCT>C,inframe_deletion|CXXC5|ENST00000302517|protein_coding|+|82YS>82Y|139680769CTCT>C  GT:AB:AD:DP:GQ:PL:RNC:SBPV:BCSQ 0|1:0.678571:57,27:84:99:973,0,2344:..:0.5529:174762

**Comment by pd3** [comment]
This happens when it is difficult or impossible to know the real life consequence.

In this case this he deletion is very close to the exon boundary (marked below as "..eee|") and the sequence looks like this:
```
...eeeee|
...CTCTT|CTTTTGGCA   ref
...C---T|CTTTTGGCA   alt
```
Notice that the deletion fills back the last codon
```
...eeeee|
...CTCTT|CTTTTGGCA   ref
...CTCTT|TTGGCA      alt
```
Moreover, in this case the transcript sequence is 3' incomplete, which adds to the complication.
http://www.ensembl.org/Homo_sapiens/Transcript/Summary?db=core;g=ENSG00000171604;r=5:139675443-139680773;t=ENST00000503511

**Comment by MWendorff** [comment]
Thanks for the clarification!
