### ISSUE TITLE
Using the -Ob command and the file is saved in vcf format.

### ISSUE THREAD

**Issue by ryandikdan** [samtools/bcftools#1561]
I was combining the gnomAD dataset and then trying to output it as BCF instead of VCF in order to save a considerably amount of space, but I noticed that the combined file was the same size as all the chromosomes combined. Then I tried to run the resultant file in plink and it said it wasn't BCF, but when I ran with the command --vcf it ran fine. Below is the code I used to combine the chromosome files. Is there something else I'm doing wrong? Does concat not output BCF?
```
srun bcftools concat --threads 32 -n -f chr_file_names.txt -Ob -o combined.gnomad.genomes.v3.1.hgdp_1kg_subset.autosomes.bcf.gz
```
where chr_file_names.txt lists the chromosomes filenames.

I'm running 1.9 for bcftools and htslib by the way.

**Comment by pd3** [comment]
This is because you used the `-n, --naive` mode and your input files are VCFs. The whole purpose of `-n` is to avoid recoding between VCF-BCF and recompression of files. I just pushed a commit that will complain if the user attempts to request incompatible output type.

Your installation of bcftools is quite old by the way, better is to use the latest version as there were many bugs fixed and improvements made.

**Comment by ryandikdan** [comment]
Got it. Thanks!
