### ISSUE TITLE
bcftools keeps getting killed

### ISSUE THREAD

**Issue by SHuang-Broad** [samtools/bcftools#1576]
Hi, 

I'm trying to concatenate and then sort a set of gVCF files.
The particular set of gVCF.gz files sum to 17GB.

After the following concatenation operation

```bash

bcftools \
    concat \
    --naive \
    -f all_raw_vcfs.txt \
    --output-type v \
    -o concatedated_raw.vcf
```

The following sort command keeps getting killed 

```bash
bcftools \
    sort \
    -m ${work_memory}G \
    --temp-dir tm_sort \
    --output-type z \
    -o ${prefix}.vcf.gz \
    concatedated_raw.vcf
```
Even when the machine has 600GB of memory.

So I am wondering
 * what am I doing wrong?
 * what memory footprint should be expected based on input file size?

Thanks!
Steve

------
bcftools version 1.13, compiled from source.

**Comment by pd3** [comment]
The default memory used by `bcftools sort` is really small
```
-m, --max-mem FLOAT[kMG]       maximum memory to use [768M]
```
so probably `${work_memory}` requests more than the job scheduler allows?

While the program is running, you can monitor how much memory it actually takes and see if it's in the requested limits.

**Comment by SHuang-Broad** [comment]
In my particular case, I allocated 600G for the work and specified `work_memory` to be 500G, so that was puzzling me.

I actually tested not specifying `max-mem` at all and it worked...

**Comment by pd3** [comment]
OK, I looked into this and found out that since `sort` keeps many bcf1_t structures allocated in the memory and each
comes with a small unused memory overhead. Just pushed a commit where we allocate a single large buffer of the maximum allowed size and memcpy the memory actually used https://github.com/samtools/bcftools/commit/1d9580c2f8c49dd96022cb854ef9a7601e784072.

Any chance you could check if this behaves on your big memory machine?

Note that the commit currently fails in tests for a different reason, cosmetic and unrelated to this.

**Comment by pd3** [comment]
This is now merged
