### ISSUE TITLE
How subtract to a vcf the result of a --complement?

### ISSUE THREAD

**Issue by arteteco** [samtools/bcftools#1617]
Hello everyone,

I think this is me not understanding the tool, not a bug.
Let's say (in a very simplified way) that I want to subtract a vcf from the other, so that, `a.vcf.gz` - `b.vcf.gz` = `c.vcf.gz`

I do that with 

```
bcftools isec --complement ---output-type z --output outFile.bed a.vcf.gz b.vcf.gz
```

The result is not a vcf but looks rather like a bed file. If I check the head I got something like

```
chr1    3232966 G       A       100000
chr1    3232976 G       C       100000
chr1    3696709 AT      A       100000
chr1    3987462 T       C       100000
chr1    4418619 G       A       100000
chr1    4557369 G       A       100000
chr1    4590408 A       T       100000
chr1    4675923 G       A       100000
chr1    4676183 C       CAGAA   100000
chr1    4863176 C       A       100000
```

Is this a bed file? 
I tried to filter this from a.vcf.gz, in a way that

```
bcftools filter --regions-file outFile.bed --output-type z --output filtered.vcf.gz a.vcf.gz
```

But I get the following error

```
Failed to open outFile.bed: unknown file type
```

I don't understand how to proceed. How can I subtract a vcf from another using isec? What file type is that, and how can I use it?

Thanks all!

**Comment by pd3** [comment]
The program prints a hint:
```
Note: -w option not given, printing list of sites...
```
Using the `-w` option one can specify which files should be sent to output. In your case only `-C -w 1` makes sense.

If you are interested why it behaves this way and why `-w 1` is not the default with `-C`, it's because the program wants to be consistent with other scenarios when multiple files are given with `-n`, then the desired output has to be selected explicitly.
