### ISSUE TITLE
concat --naive drops headers present in subset of VCFs

### ISSUE THREAD

**Issue by SHuang-Broad** [samtools/bcftools#1629]
I'm seeing some FILTER definitions dropped.

```
$ bcftools --version
bcftools 1.13
Using htslib 1.13
```

**Comment by pd3** [comment]
Can you try with the latest version (1.14)? Using that should result in an error. The `--naive` option is intended for merging files with the exact same headers where the order and presence of all tags is identical. This is because in case of BCF the header implicitly defines tag ids used throughout the body.
