### ISSUE TITLE
bcftools error related to libdeflate.so

### ISSUE THREAD

**Issue by awaller2** [samtools/bcftools#1643]
Im trying to run bcftools on a Mac running Mojave and am getting erros related to libdeflate.so.

I've looked at a similar issue and tried the suggestions https://github.com/samtools/bcftools/issues/1434.

I've updated conda, added the conda-forge channel "conda config --add channels conda-forge"
this is how I installed bcftools
conda install -c bioconda -c conda-forge bcftools

Here is my command:
bcftools mpileup -O b -f data/ref_genome/ncbi_dataset/data/GCF_000001405.39/chr1.fna chr1.subset.bam

Here is my error message:
dyld: Library not loaded: @rpath/libdeflate.so
  Referenced from: /Users/alisonwaller/miniconda3/bin/bcftools
  Reason: image not found
Abort trap: 6

any suggestions ? thanks

**Comment by jmarshall** [comment]
> Referenced from: /Users/alisonwaller/miniconda3/bin/bcftools

You have installed bcftools into your existing **base** Conda environment, and existing packages already installed in that environment have meant that an outdated version of bcftools built against a now-incompatible version of libdeflate has been installed.

As suggested in https://github.com/samtools/bcftools/issues/1434#issuecomment-785804721, you should install bcftools into a fresh environment (unless you are willing to figure out which packages in an existing environment are holding it back):

```
conda create -n bcftools_env bcftools
conda activate bcftools_env
```

**Comment by awaller2** [comment]
Great.  That worked, but now I"m getting an error.  Not sure if you can help:
Here is my command:
bcftools mpileup -O b -f data/ref_genome/ncbi_dataset/data/GCF_000001405.39/chr1.fna chr1.subset.bam
Here is the error:
[E::faidx_adjust_position] The sequence "chr1" was not found

the file path to the fasta file is correct:

head data/ref_genome/ncbi_dataset/data/GCF_000001405.39/chr1.fna
>NC_000001.11 Homo sapiens chromosome 1, GRCh38.p13 Primary Assembly
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

**Comment by jmarshall** [comment]
Your BAM file has been mapped against a reference with sequences with names like “chr1” but _chr1.fna_ has sequences with names like “NC_000001.11”. There are ways to rename one or the other so that the names are the same, but the recommended thing to do would be to use the same FASTA reference file for `mpileup -f` as was used when the BAM file was aligned/mapped.

**Comment by awaller2** [comment]
okay I downloaded the reference fasta from ucsc so its called chr1 now.  
when I perfomed this:
bcftools mpileup -O b -f chr1.fa chr1.subset.bam
I got crazy binary speak on the terminal.
then I tried this :
bcftools mpileup -O b -f chr1.fa chr1.subset.bam
and got this:
Does the file "chr1.subset.bam" really contain a list of files and do all exist?
bcftools mpileup -O b -f chr1.fa -b chr1.subset.bam

I was just given a bam file that was mapped to chr1 and I want to call variants.  Am I incorrectly using the bsftools syntax or is there something else I'm missing ?
Thanks

**Comment by jkbonfield** [comment]
>  when I perfomed this:
> bcftools mpileup -O b -f chr1.fa chr1.subset.bam
> I got crazy binary speak on the terminal.
> then I tried this :
> bcftools mpileup -O b -f chr1.fa chr1.subset.bam
> and got this:

Those two commands are identical (and later a 3rd idential one).  Which is wrong?

The "crazy binary speak" is simply because you're asking for BCF (the B is for "binary") to be sent to stdout.  The default is -Ov for (text) VCF output, which makes sense for manual inspection.

If you want to call variants, you'll need to do `mpileup` piped into `call`.  I recommend following the instructions on https://www.htslib.org/workflow/wgs-call.html

It is perfectly valid to only do a single chromosome, either by specifying a region of a much larger file (`bcftools mpileup -r` _region_) or simply by having an input BAM file that's already been cut down to just a single chromosome.  Don't worry if the headers list all the `@SQ` lines or `##contig` lines.  The headers don't change when selecting a smaller region.

**Comment by pd3** [comment]
I believe this is now resolve, closing the issue now.
