### ISSUE TITLE
Differing behaviour between --include and --exclude

### ISSUE THREAD

**Issue by jethror1** [samtools/bcftools#1677]
I am trying to filter a VCF using `bcftools filter` and trying out various parameters for filtering. I am testing with a VCF annotated using VEP, which includes various population AFs including gnomAD. For this, I would like to start by filtering against the gnomAD AF, and have behaviour with bcftools that doesn't seem to be documented.

When doing `bcftools -e 'gnomAD_AF>0.02'` and `bcftools -i 'gnomAD_AF<0.02'`, I was expecting to return the same variants (i.e. everything with an AF under 2%).  The gnomAD AF looks to contain some missing values (represented by `'.'`) for some of these variants. When filtering `-e` these variants are retained, whereas with `-i` these are excluded. Is this expected behaviour? I would have thought these should return the same results, and can't find an explanation in the documentation to describe the differences.

```
$ bcftools filter -i 'gnomAD_AF<0.02' NA12878.split.vcf > test_include.vcf
$ bcftools filter -e 'gnomAD_AF>0.02' NA12878.split.vcf > test_exclude.vcf

$ grep -v '^#' NA12878.split.vcf | wc -l
23236
$ grep -v '^#' test_include.vcf | wc -l
681
$ grep -v '^#' test_exclude.vcf | wc -l
9144
```
Confirming missing values only present in `-e` vcf:
```
$ grep  "gnomAD_AF=\." test_include.vcf | wc -l
0

$ grep "gnomAD_AF=\." test_exclude.vcf | wc -l
8463
```

Using versions:
```
$ bcftools --version
bcftools 1.14-30-g21abb46
Using htslib 1.14-13-g965a90c
```

**Comment by jkbonfield** [comment]
Note `>` and `<` aren't precisely opposites.  You'd need something like `>` and `<=` when double checking stats.  However the missing values are really the issue here.

 It feels like it's working though.  With -i you're saying to only include values < 0.02 and a missing value isn't less than anything, so shouldn't pass the filter.  Conversely with -e you're rejecting values above 0.2 which again won't reject missing values as they're also not larger than a specific amount.  Hence why their inclusion differs.

I don't know if it's possible to do something like `gnomAD_AF <0.2 || gnomAD_AF = "."` to explicitly include missing values and create a more symmetric filter.

**Comment by pd3** [comment]
That is correct. Missing values cannot be compared and therefore must be either dealt with explicitly (`gnomAD_AF <0.2 || gnomAD_AF = "."`) or implicitly by using the suitable logic. In fact, the complementary `-i`/`-e` logic was intended exactly for this, so that one can simply reverse the logic to get the desired result without making the expression too complex.
