### ISSUE TITLE
split-vep could not recognize M-CAP

### ISSUE THREAD

**Issue by zofieLin** [samtools/bcftools#1686]
Hi,

I am using bcftools +split-vep to extract the M-CAP score from the vcf annotated by VEP, but it could not recognize and produced error below:
![image](https://user-images.githubusercontent.com/51777970/159667249-eaf3db27-6a81-41c5-8a9a-7e33a9006b20.png)

I checked with `bcftools +split-vep *.vep.vcf.gz -l `, "M-CAP_score" was actually present in the CSQ field. 
![image](https://user-images.githubusercontent.com/51777970/159665434-ae365aad-0f18-46c4-8a83-085cef2d2e36.png)

I also tired with some other typos, but all didn't work. Are there any solutions to solve this problem?
![image](https://user-images.githubusercontent.com/51777970/159668602-eea81939-a9e8-4a2a-a832-777bb713371d.png)

Thanks!

**Comment by pd3** [comment]
This is caused by the dash which is not considered a valid tag name character by VCF specification. This is a problem because `+split-vep` treats internally VEP fields as VCF tags and this breaks the `query` format expression.

A quick workaround is to edit the header and replace with underscores, e.g. `M_CAP_pred`. See the `reheader` command.

The program could be also made smarter and replace such characters automatically. Could you please show the VEP line from the header and a single data line for debugging?

**Comment by pd3** [comment]
This is now addressed, offending characters are replaced with underscores. Please try it out

**Comment by zofieLin** [comment]
Thank you so much, it worked well, with "%M_CAP_pred".

**Comment by hanguojun007** [comment]
See the reheader command.
where is the `reheader` ? I can't find it.

**Comment by hanguojun007** [comment]
Hi, I try `reheader`, but it just replace the header, not the INFO content.
when I `query`  the new header, i can't get the value. because the header of INFO does not change.

**Comment by pd3** [comment]
@hanguojun007 This would have to be done _before_ the plugin is run.

For example the VEP definition
```
##INFO=<ID=CSQ,...,Description="Format: Allele|Consequence|..|M-CAP_pred|...">
```
would be changed to
```
##INFO=<ID=CSQ,...,Description="Format: Allele|Consequence|..|M_CAP_pred|...">
```
with reheader, the `+split-vep` would work.

With the latest version this is not needed anymore.
