### ISSUE TITLE
Cannot define an exact match of FILTER to multiple flags

### ISSUE THREAD

**Issue by ImNotaGit** [samtools/bcftools#1719]
I am using bcftools version 1.14. After reading the documentation and some search online I still cannot figure out how to define an exact FILTER match to multiple flags, e.g. I would like to select variants whose FILTER is exactly "A;B" (not "A", not "B", not "A;B;C", etc.). When I do `FILTER="A;B"` I get the error `The filter "A;B" not present in the VCF header`. FILTER flag "A" and "B" are both defined in the header. Just for testing if I add a FILTER definition for "A;B" into the header, the program runs without error but the "A;B" cases were not matched, so basically it doesn't work.

**Comment by pd3** [comment]
Your observation is indeed correct, but note that filter names cannot contain semicolons, so that would never work. Also the filters can appear in arbitrary order, so searching for exact string match would not be robust.

What should work, sort of, is `FILTER~"A" && FILTER~"B"` for the two filters set. However, this would also filter sites with `FILTER="A;B;C"`.

I'll mark this as enhancement. What we want is extend the matching to multiple values so that `FILTER=="A;B;C"` and `FILTER~"A;B"` would match `A;B;C` with A,B,C in arbitrary order.

**Comment by pd3** [comment]
This is now supported, the FILTER column can be now queried as follows:

```
        FILTER="PASS"
        FILTER="."
        FILTER="A"          .. exact match, for example "A;B" does not pass
        FILTER="A;B"        .. exact match, "A;B" and "B;A" pass, everything else fails
        FILTER!="A"         .. exact match, for example "A;B" does pass
        FILTER~"A"          .. subset match, for example both "A" and "A;B" pass
        FILTER~"A;B"        .. subset match, pass only if both "A" and "B" are present
        FILTER!~"A"         .. complement match, for example both "A" and "A;B" fail
        FILTER!~"A;B"       .. complement match, fail if both "A" and "B" are present
```

**Comment by ImNotaGit** [comment]
Thanks a lot for addressing this so quickly!
