### ISSUE TITLE
is there a way to extract the list of contigs using bcftools index from index files generated by old versions of tabix?

### ISSUE THREAD

**Issue by freeseek** [samtools/bcftools#1771]
```
$ wget https://ftp.ncbi.nih.gov/snp/latest_release/VCF/GCF_000001405.39.gz.tbi
$ bcftools index --stats GCF_000001405.39.gz.tbi
```
This does not generate anything. However, the list of contigs could be something useful for the user to be able to retrieve, even if the number of variants per contig is not available. For this specific example, the following code extracts this list:
```
$ zcat GCF_000001405.39.gz.tbi | strings | grep "^NC_\|^NT_\|^NW_" | head
NC_000001.11
NC_000002.12
NC_000003.12
NC_000004.12
NC_000005.10
NC_000006.12
NC_000007.14
NC_000008.11
NC_000009.12
NC_000010.11
```
However, this does not generalize to other index files generated by old versions of tabix

**Comment by jkbonfield** [comment]
I've never quite understood how all the index formats fit together for bcftools!  `bcftools index foo.vcf.gz` generages a .csi file and not a .tbi, and `bcftools index --stats goo.vcf.gz.csi` works as expected.    However it also works for me on a tabix produced file (I tried both 1.15 and 1.3).

I found an ancient copy of tabix (0.2.6) from before htslib and it produces an incompatible format.  I wasn't even aware tabix had changed formats over the years.   Sure enough bcftools can't get stats from that one.  Sadly `htsfile` cannot distinguish between old and new tabix indices, likely because they have the same magic number with different internal meta-data blocks.  (Definitely a case of "I wouldn't start from here"...)

Personally I'd say the correct solution is reindexing these files with something other than an archaic version of tabix.  Even a 10 year old tabix would probably do!  I'm not sure we really wish to be supporting such legacy index formats, especially given there's zero documentation on it from what I can see.  That's something NCBI need to do though, so I feel your pain.

Meanwhile, it's probably more robust to just pull the list of contigs out of the VCF file rather than trying to navigate the twisty maze of index file formats all alike:

```
bcftools view --header-only https://ftp.ncbi.nih.gov/snp/latest_release/VCF/GCF_000001405.39.gz|sed -n 's/##contig=<ID=\(.*\)>/\1/p'
```

**Comment by freeseek** [comment]
Unfortunately for this particular VCF the contigs are not listed in the header. The only way to get the list of contigs is either parse the whole 24GB gzip compressed file (which takes a very long time) or somehow manually interpret what is contained in the tabix indexed file. I am actually shocked that after >10 years the genetic community is still using the `.vcf.gz` rather than the `.bcf` file format. Some VCFs are now much bigger than BAM files used to be when the `.bam` file format was introduced. I do not understand what the point of consuming users' time while waiting for commands to parse endlessly long text files is

**Comment by jmarshall** [comment]
One of these ~~days~~ years I'll get around to finishing writing up better documentation of the index formats.

Presumably `bcftools index --stats` doesn't print anything because this index file doesn't have any metadata pseudo-bins containing the read stats. However to get the list of contigs you only need to read the `.tbi` header, for which the following will work better than `strings + grep`:

```sh
zcat GCF_000001405.39.gz.tbi | \
    perl -e 'read(STDIN,$_,36); read(STDIN,$_,unpack "x32V"); tr /\0/\n/; print'
```

**Comment by jmarshall** [comment]
As I suspected, the problem is not that there is any real incompatibility in the format but simply that this index file was generated before metadata pseudo-bins were commonly emitted in _.tbi_ indexes.

Hence `bcftools index --stats` omits all the contigs because they have zero record counts. PR #1772 adds an option so that the following will do the trick:

```
bcftools index --stats --all GCF_000001405.39.gz.tbi
```
