### ISSUE TITLE
could bcftools have a command to change the IDs of the variants?

### ISSUE THREAD

**Issue by freeseek** [samtools/bcftools#178]
It would be nice if bcftools was capable to change the IDs of the variants to give users a way to make these unique. There are many VCF files out there where variant names are not unique and this causes issues. It is also the case that when multiallelic variants are split with bcftools norm the name uniqueness is affected.

My suggestion would be to add a feature in bcftools norm which could assign IDs on the fly. Something like:
bcftools norm -n, --name <string>
where string could be a typical bcftools string, so that for example I could run:
bcftools norm -n '%CHROM_%POS_%REF_%ALT' file.vcf.gz
to assign names to each variant and make the IDs unique.

This would help for example when converting VCF files to plink format in such a way that people could seamlessly merge and compare them even after conversion to plink (see http://bit.ly/1sgOcuP).

**Comment by pd3** [comment]
OK, this feature has been added (9b0e7ccf), it can be used as: 

      bcftools annotate --set-id +'%CHROM\_%POS\_%REF\_%FIRST_ALT'  file.vcf

**Comment by CristianRiccio** [comment]
Hi, 
Thank you for adding this functionality. However, can you please explain to me how to use this function?

I have run this:

samtools mpileup -t DP -u -F -m --fasta-ref celegans.fa --bam-list pathsToSortedBams.txt | bcftools call -m -v -O v > variants.vcf

and so my VCF file has paths for the columns realted to sample information. I would like instead to rename those columns to something else, with a new set of IDs. Where does this new set come from in:

  bcftools annotate --set-id +'%CHROM\_%POS\_%REF\_%FIRST_ALT'  file.vcf

?

Or can I make samtools mpileup name my samples as I wish in the first place instead of using the paths to the BAM files?
Thanks.
Best wishes,
C.

**Comment by pd3** [comment]
This thread was about something else. I think you just want to rename the samples, which can be done using the `bcftools reheader` command: http://samtools.github.io/bcftools/bcftools-man.html#reheader

**Comment by Eduardo-Auer** [comment]
> OK, this feature has been added ([9b0e7cc](https://github.com/samtools/bcftools/commit/9b0e7ccfb13b093ad4809e1417f7130899d43b6d)), it can be used as:
> 
> ```
>   bcftools annotate --set-id +'%CHROM\_%POS\_%REF\_%FIRST_ALT'  file.vcf
> ```

Hello, is it possible to use it only when there is no dbSNP ID annotation? For example, is there a way to only annotate this ID when the variant ID is "."?

**Comment by mpage21** [comment]
> > OK, this feature has been added ([9b0e7cc](https://github.com/samtools/bcftools/commit/9b0e7ccfb13b093ad4809e1417f7130899d43b6d)), it can be used as:
> > ```
> >   bcftools annotate --set-id +'%CHROM\_%POS\_%REF\_%FIRST_ALT'  file.vcf
> > ```
> 
> Hello, is it possible to use it only when there is no dbSNP ID annotation? For example, is there a way to only annotate this ID when the variant ID is "."?

I agree with this. It would be super helpful. @pd3 is there a current way we can do this? Or could this functionality be added?

**Comment by pd3** [comment]
Did you actually try the command shown above (https://github.com/samtools/bcftools/issues/178#issuecomment-70852614) or read the man page (http://samtools.github.io/bcftools/bcftools.html#annotate)?

It says
```
If the format string is preceded by "+", only missing IDs will be set
```

You can also combine with `-i, --include` and `-k, --keep-sites` to fine tune the behavior, for example
```
bcftools annotate --include 'ID!~"^rs"' --keep-sites -set-id '%CHROM\_%POS\_%REF\_%FIRST_ALT' file.vcf
```

**Comment by mpage21** [comment]
@pd3 Thank you for your response. I did read the man page (haven't tried the command shown yet because of how big my file is). I guess I am confused as to if the command above that you included works also with the --annotations _file_ flag. The vcf I'm using has some lines that correspond to rsIDs in the annotations file I pass and some that don't. When it says 'only missing IDs will be set" would that be after it can't find that position in my annotations file, then (in the same command) it would set it to what I ask?

So essentially, would this be a valid command that would fill in the ID column with the rsID if it exists in the annotation file and with the chrom:pos:ref:first_alt if it doesn't? This is what I understood @Eduardo-Auer's question to be asking. 
`bcftools annotate --annotations annotation.vcf.gz -c ID --set_id +'%CHROM:%POS:%REF:%FIRST_ALT' -o outfile.vcf.gz file.vcf.gz`

**Comment by pd3** [comment]
Mm, if the VCF is big, the best way to approach this is to test on a small region first...

But yes, it should work.

**Comment by mpage21** [comment]
Thank you!

I did as you suggested and tested on a small region first. This worked in the manner that I hoped it would.

**Comment by Eduardo-Auer** [comment]
> Did you actually try the command shown above ([#178 (comment)](https://github.com/samtools/bcftools/issues/178#issuecomment-70852614)) or read the man page (http://samtools.github.io/bcftools/bcftools.html#annotate)?
> 
> It says
> 
> ```
> If the format string is preceded by "+", only missing IDs will be set
> ```
> 
> You can also combine with `-i, --include` and `-k, --keep-sites` to fine tune the behavior, for example
> 
> ```
> bcftools annotate --include 'ID!~"^rs"' --keep-sites -set-id '%CHROM\_%POS\_%REF\_%FIRST_ALT' file.vcf
> ```

Thank you so much for your help!

**Comment by mbhall88** [comment]
Is there a way to set a [UID](https://en.wikipedia.org/wiki/Unique_identifier) as the ID?
