### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by pd3** [samtools/bcftools#1813]
Hi sorry for opening up this issue again but I have a question regarding the fix of changing the tag `Number=.` .

In my case I'm working with a raw TCGA germline data VCFv4.2 and using bcftools 1.16 . 

I first filtered my .vcf to only keep the variants with 'FILTER="PASS"' to then split the .vcf due to the multivariants, but I the following error pretty early:

`Error: wrong number of fields in FMT/AD at 1:15053, expected 31167, found 20778`

I've tried to take a look at what may be missing but I don't understand why it's returning such as big number for AD and its something that I must keep. 

If I try the `Number=.` would it affect further steps of my annotation pipeline? Because I'm not sure that working with a .vcf file with different number of fields across variants could lead to further errors...

Thanks in advance and sorry if this is a basic question~!

_Originally posted by @ManuelMoradiellos in https://github.com/samtools/bcftools/issues/1131#issuecomment-1303425668_

**Comment by pd3** [comment]
It's probably because there are many samples in the VCF and the error message reports the total number of AD values across all samples. There could be different reasons for the mismatch, it is not possible to check without seeing the file. Modifying to `Number=.` only hurts if 1) someone is going to work with AD values downstream 2) the VCF is malformatted in some severe way (e.g. fewer sample columns at that line).

If you think it's bug, please provide a small test case
```
cat your-file.vcf | awk '$1~/^#/ || ($1=="1" && $2==15053)'  > test-case.vcf
```

**Comment by ManuelMoradiellos** [comment]
Hi!

Thanks for the quick response and sorry for replying to a closed issue instead of opening a new one; I didn't want to cause any trouble.

As later I need to work with the AD values to filter out some variants with low quality I would not do the `Number=.` fix, so maybe its malformatted but the source of the .vcf told me that they didn't had any issue when working with this raw file and that they were able to annotate perfectly!

So here I provide the small test case (_in .txt because of GitHub_):

[test-case.mmoradiellos.txt](https://github.com/samtools/bcftools/files/9940028/test-case.mmoradiellos.txt)

Thanks for all the help~<3

**Comment by pd3** [comment]
So the problem is indeed that some samples have incorrect number of AD values:
```
bcftools query test-case.mmoradiellos.txt -f '[%REF %ALT %AD\n]' -i 'AD!="."' | head 
C T,G 13
C T,G 15
C T,G 10
C T,G 21
C T,G 7
C T,G 6
C T,G 5
C T,G 12
C T,G 20,7
C T,G 21
```
This needs to be fixed upstream, bcftools is correct in refusing to work.
