### ISSUE TITLE
--targets-overlap --regions-overlap not recognized by mpileup

### ISSUE THREAD

**Issue by barissalman** [samtools/bcftools#1817]
Hi,
mpileup does not recognize the overlap options.
They re not in the source either.
https://github.com/samtools/bcftools/blob/develop/mpileup.c
Best,
B

**Comment by pd3** [comment]
This is a statement, not a question or a bug report, therefore I'll assume you want to know why and you are asking if the options can be added.

The reason is that filtering by region is done on the input stream, rather than output stream, and the `bcftools mpileup` takes on input alignment files, not VCFs. Although we could apply the logic on the VCF output in principle, that has not been done for two reasons. First, the indels are not normalized and, second, one can simply stream through `bcftools view` to achieve the same result. Therefore we are not planning to add the options.

**Comment by barissalman** [comment]
Hi,
thanks for the clarification. I got confused because these options are present in the documentation for mpileup https://samtools.github.io/bcftools/bcftools.html#mpileup. 

Here is my case, I got this bam file with the following bed file:
[test_files.zip](https://github.com/samtools/bcftools/files/10022602/test_files.zip)

Bed file:
chr13   48923060        48923189

I am trying the call the variant:
chr13   48923056        .       TTCCTGTTTTTTTTCTGCTTTCTATTTGTTTAAT      TT 

Variant overlap with the bed entry. My exception is that running mpileup with -R to include the variant since by default -R should include the overlapping variants.
![image](https://user-images.githubusercontent.com/47355527/202207311-3cfda671-9011-4db5-9d9f-281dacdf835e.png)

However as you mention -R or -T options doesn't include these variants.
![image](https://user-images.githubusercontent.com/47355527/202209168-5f68339a-b95a-4473-a1da-893b1f669370.png)
![image](https://user-images.githubusercontent.com/47355527/202212664-41c4be90-4cab-476d-9ae5-377c6856181c.png)

Your approach does call the variants as expected (using -T here with --targets-overlap 1 since bcftools expect vcf to be bgzipped and indexed):
![image](https://user-images.githubusercontent.com/47355527/202210517-e5984b74-64c1-46f8-b504-dba2aa7dcb2c.png)

It's much clear but one remark is that bcftools call also doesn't support the --targets-overlap/--regions-overlap option like mpileup.

Best,
B

**Comment by pd3** [comment]
Yes, `call` is another example. There the reason is that the `-T` option is also internally implemented differently, as it is used with `-C`, and on input indels are typically also not normalized.
