### ISSUE TITLE
Does bcftools support `--write-index` like samtools?

### ISSUE THREAD

**Issue by SHuang-Broad** [samtools/bcftools#1853]
Hi,

I'm wondering `bcftools` supports an option like what samtools [does](https://github.com/samtools/samtools/issues/1196).
I've searched on the manual page and the Issues page here but nothing related returns.
(There's an option to specify custom index for inputs, though).

Having this option will save a little coding effort (no more need for explicit indexing right after various operations).

Thank you,
Steve

**Comment by pd3** [comment]
Unfortunately not. It would require quite a bit of coding effort and has not been done yet.

**Comment by pd3** [comment]
This is htslib dependent, cross-referencing it here https://github.com/samtools/htslib/issues/1555

**Comment by jkbonfield** [comment]
It turns out this feature was written back in 2018!  https://github.com/samtools/htslib/pull/718

It exists and works in htslib's test/test_view program.  What's missing is bcftools command line support.  Given it's therefore a far easier (maybe!) problem than I thought, I've made a first stab at doing that.

What's trickier is working out if it works!  I can see some differences in the vcf.gz csi index, but haven't the foggiest what the differences mean.  I think the last time I did this I spent hours staring at hex dumps.  If anyone has a vcf debug tool (and bai, and tbi, and whatever random hybrids between them exists) it'd be helpful.  Otherwise I'll probably give up and write one.

**Comment by pd3** [comment]
That's great, sorry I missed VCF/BCF was already supported. I am happy to add the bcftools side of things, but I am not aware of a TBI/CSI debugging tool. I am thinking it might be useful to add a new `tabix --dump-index` option that would print the content of an index in a human readable and verifiable form?

**Comment by jkbonfield** [comment]
Rob reminded me that Valeriuo added one.  Just build htslib with `-DDEBUG_INDEX`.

I have a branch of bcftools with --write-index already, but I'm tearing my hair out understanding the myriad of index variants.  Can you clarify, for each format, what index types we actually support for reading, and for writing?  Eg I cannot find anyway whatsoever of writing a bai index, yet I swear it supports them.

**Comment by pd3** [comment]
It's only tbi and csi

**Comment by jkbonfield** [comment]
For what? Writing or reading?

**Comment by pd3** [comment]
I only encountered TBI and CSI with VCF/BCF files, for both reading and writing.

**Comment by jkbonfield** [comment]
Presumably there were BAI at some point though, as `bcftools index` has a `-c` option to output CSI (now default).  It wouldn't exist if it always only ever supported CSI.

Anyway, probably it doesn't matter as it's writing that matters and if we don't support writing BAI then that's fine.

**Comment by pd3** [comment]
That is to distinguish from TBI. Alignment files had BAI, then came CSI. VCF files had TBI, then came CSI.

**Comment by pd3** [comment]
The support has been now added in 9b352b7c5431b5cbb33dd5141864c389a1c8e0a0
