### ISSUE TITLE
bcftools +fill-tags fails on Thousand Genomes VCF file

### ISSUE THREAD

**Issue by holtgrewe** [samtools/bcftools#1857]
To reproduce, use the file from here:

https://ftp-trace.ncbi.nih.gov/1000genomes/ftp/phase3/integrated_sv_map/ALL.wgs.integrated_sv_map_v2.20130502.svs.genotypes.vcf.gz

Call like this:

```
bcftools +fill-tags -t INFO/AC_Hom,INFO/AC_Het vardbs/GRCh37/struc-var/download/ALL.wgs.mergedSV.v8.20130502.svs.genotypes.vcf.gz -O z -o xs.vcf.gz
```

And you see that only the header line is called.

This is bcftools v1.16 on x86_64 Linux from the bioconda channel.

**Comment by pd3** [comment]
It turns out there are two problems. First is in the rather unintuitive way the plugin must be run
```
bcftools +fill-tags input.bcf -- -t AC_Hom
```
note the double dash `--` which separates general and plugin-specific options, in this case `-t, --tags`. When run as
```
bcftools +fill-tags input.bcf -t AC_Hom
```
the program interprets the option as `-t, --targets` and, looking for chromosome named `AC_Hom`, skips everything else.

Second problem is that from some reason the usage page advertises as valid `-t INFO/AC_Hom` but in fact recognizes only `-t AC_Hom`. In the commit pushed just now this is fixed and the both forms will be accepted https://github.com/samtools/bcftools/commit/d61277ecceb6c63f2ec2d3083e409bd91b608446.

Thanks for the issue.
