### ISSUE TITLE
Different singleton counts between bcftools and vcftools

### ISSUE THREAD

**Issue by bchak10** [samtools/bcftools#1868]
Hello, the singleton stats generated by bcftools and vcftools for the exact same VCF appear to be different:

With bcftools I’m using `bcftools stats` and looking at the SiS line field [4]; with vcftools I’m using `vcftools --gzvcf --singletons` and the output is a list of singletons and private doubletons. I filtered just for the singletons and those counts generated by bcftools vs. vcftools do not match up. I am getting 222544 vs. 223570. 

Would appreciate any explanation for how these counts are generated in the backend and potential causes for the discrepancy, thank you!

**Comment by pd3** [comment]
I don't know what `vcftools` does but my best guess is that this is due to the fact that `bcftools stats` counts alleles rather than sites at multiallelic sites. So for example if the first and second alternate allele appear only once across all samples, the `1/2` genotype would be counted as two singletons.
