### ISSUE TITLE
[Feature Request] Allow --write-index to choose tbi index output

### ISSUE THREAD

**Issue by rickymagner** [samtools/bcftools#2008]
Hi,

This is a small feature request that `--write-index` take an optional parameter to allow it to write `.tbi` index files if desired. Something like `--write-index tbi` or `--write-index t` would be great to have since currently the flag just outputs `.csi` indices. I looked through the code a little and it wasn't obvious how this flag gets parsed and used, but if anyone could offer some guidance on where the code might have to be updated to add this, I could take a look at adding the feature.

**Comment by jkbonfield** [comment]
I was looking at this the other day infact and I'm totally confused with what it's trying to do.

I managed to get both a .csi and a .tbi file that were totally identical except for filename!  I think perhaps bcftools is just bugged here, and it is infact already writing tbi.

**Comment by SHuang-Broad** [comment]
upvote on this
It sounds like a fix that's easy to do?

**Comment by Smeds** [comment]
It would be great if this could be solved soon=)

**Comment by Smeds** [comment]
Looked at the code, for bcftools view, where I only have been able to get a csi file as index output. And from what I can understand the write_index functions is called at:
https://github.com/samtools/bcftools/blob/ddc1a3774ca222504c3901b35bae06e8b3fd18e5/vcfview.c#L810

and it takes my `vcf.gz` output file name as input

https://github.com/samtools/bcftools/blob/ddc1a3774ca222504c3901b35bae06e8b3fd18e5/version.c#L116-L141

It uses strstr to determine if `##idx##`can be found in the filename and in that case it will write a `idx` file instead of a `csi` file. I will probably not have `##idx##` in my filename and therefor never get a tbi file, or have I misunderstood the code?

**Comment by jkbonfield** [comment]
You're correct that it auto selects the format based on the 2-part name.  The `##idx##` is a way of specifying two filenames in an argument that was originally designed to only have one.  One use is for fixing tools that miss out the file format from the filename, eg "foo.bam" and "foo.bai", but I think the original purpose was with object stores where filenames can just become hashes so the index name has absolutely no relationship to the filename!

However it's now also been repurposed to permit foo.bam and foo.bam.csi.  Basically just specifing `filename##idx##indexfilename`.  Eg `foo.vcf.gz##idx##foo.vcf.gz.tbi` and you'll get two files: `foo.vcf.gz` and `foo.vcf.gz.tbi`.

I agree this is a ghastly syntax, but there wasn't a great deal of easy options given an additional requirement turning up well after the CLI had become pretty much fixed.

I'll consider looking at `--write_index=tbi` with an `optional_argument` long-opts.
