### ISSUE TITLE
Latest --indel-cns code fails to call hom-ref genotypes when one sample has an insertion 

### ISSUE THREAD

**Issue by pd3** [samtools/bcftools#2130]
A test case was added here https://github.com/pd3/mpileup-tests/commit/4e309e83e6d8c4905e4f1435de06acd2234c53ef, the problem can be reproduced with
```
cd mpileup-tests/dat

bcftools mpileup --indels-cns -a AD -t chr:101 -f indels/trio-missed-homref.fa indels/trio-missed-homref.bam |
  bcftools query -f '%CHROM:%POS %REF %ALT [ %PL]'
```
For the indel line it results in missing genotypes for non-indel samples
```
chr:101 TCCCCCCC TCCCCCCCC  146,0,130 0,0,0 0,0,0
```
instead of the expected homref genotype
```
chr:101 TCCCCCCC TCCCCCCCC  255,0,182 0,129,246 0,120,255
```

**Comment by jkbonfield** [comment]
Thanks.  This is probably one of those cases of lack of testing with multi-sample calling sets as at the time I just didn't have any way of validating it.  I now better understand use of trio truth sets though which helps.

Anyway, the bug is obvious now I look.   For one sample, we will call "type=1" if we find enough data with a 1bp insertion.  Then we compute the consensus for type 0 (ref) and type 1 from the reads containing that insertion.  Easy enough.  However when we have multiple samples involved we can be attempting to compute the consensus for type 1 for a sample that has 0 evidence, and we don't get the insertion in the consensus.  Hence aligning to type=0 cons and type=1 cons gives the same scores and all reads get discarded as being uninformative. 

With hindsight the error is obvious.  We should always have the indel type included in the consensus as that's our working hypothesis, and I *thought* the data would naturally imply this due to not thinking how multi-sample calling works.  A fix for this is trivial, but I need to check for deletions and further investigate the issue.

```
diff --git a/bam2bcf_edlib.c b/bam2bcf_edlib.c
index b3ef4a8e..cd1eb08f 100644
--- a/bam2bcf_edlib.c
+++ b/bam2bcf_edlib.c
@@ -676,6 +676,16 @@ static char **bcf_cgp_consensus(int n, int *n_plp, bam_pileup1_t **plp,
             int max_v_ins = 0, max_j_ins = 0;
             int tot_ins = 0;
             for (j = 0; j < NI; j++) {
+                if (type > 0 && i+left == pos+1) {
+                    if (cons_ins[i].len[j] < type) {
+                        cons_ins[i].str[j] = realloc(cons_ins[i].str[j], type+1);
+                        memset(cons_ins[i].str[j] + cons_ins[i].len[j],
+                               'N', type - cons_ins[i].len[j]);
+                        cons_ins[i].len[j] = type;
+                    }
+
+                }
                 if (!cons_ins[i].str[j])
                     break;
                 if (cons_ins[i].freq[j] == 0)
```
```
