### ISSUE TITLE
bcftools stats DP

### ISSUE THREAD

**Issue by fan040** [samtools/bcftools#2188]
![image](https://github.com/samtools/bcftools/assets/166574153/12089d35-ea39-4e5c-b4ba-479fae1530b1)
I want to know what the third column means and what the fourth and fifth columns have no value.
![image](https://github.com/samtools/bcftools/assets/166574153/54ec08f3-c7ee-4a84-b760-981997937f35)
I want to know the meaning of this statistic, how is it calculated

**Comment by pd3** [comment]
The column [3] is the bin size, i.e the depth with the default parameters; [4-5] are per-sample FORMAT values; and [6-7] are per-site INFO values.

By default the stats are collected only for sites, i.e. for INFO fields but not for FORMAT fields. That is why 4-5 are empty in your screenshot. With `-s -`, rather counterintuitively, the program parses also FORMAT fields. (This is an example of bad design, one would expect `-s -` switches sample stats off rather than on.)

For the definition of transitions and transversions see here https://en.wikipedia.org/wiki/Transversion and https://en.wikipedia.org/wiki/Transition_(genetics). The repeat consistent/inconsistent stats was experimental and useless and will be deprecated. 

The commit [379e1b6](https://github.com/samtools/bcftools/commit/379e1b6f66721e3f39e80c6c408d806f59befaf4) extends the description to make the file format self-descriptive.

I hope this helps.

**Comment by fan040** [comment]
I want to ask the size of the bin column refers to the size of the window, right? Is it the statistical result of the various data in 1bp?

**Comment by fan040** [comment]
> The column [3] is the bin size, i.e the depth with the default parameters; [4-5] are per-sample FORMAT values; and [6-7] are per-site INFO values.
> 
> By default the stats are collected only for sites, i.e. for INFO fields but not for FORMAT fields. That is why 4-5 are empty in your screenshot. With `-s -`, rather counterintuitively, the program parses also FORMAT fields. (This is an example of bad design, one would expect `-s -` switches sample stats off rather than on.)
> 
> For the definition of transitions and transversions see here https://en.wikipedia.org/wiki/Transversion and https://en.wikipedia.org/wiki/Transition_(genetics). The repeat consistent/inconsistent stats was experimental and useless and will be deprecated.
> 
> The commit [379e1b6](https://github.com/samtools/bcftools/commit/379e1b6f66721e3f39e80c6c408d806f59befaf4) extends the description to make the file format self-descriptive.
> 
> I hope this helps.

I want to ask the size of the bin column refers to the size of the window, right? Is it the statistical result of the various data in 1bp?

**Comment by pd3** [comment]
The bin size is by default equal to 1, meaning each bin number corresponds to the coverage. See also the option 
```
 -d, --depth INT,INT,INT          Depth distribution: min,max,bin size [0,500,1]
```
