### ISSUE TITLE
bcftools --regions-file <file> can pull variants more than once and generate unsorted VCFs (even if <file> is sorted)

### ISSUE THREAD

**Issue by freeseek** [samtools/bcftools#221]
(echo "##fileformat=VCFv4.1"
echo -e "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO"
echo -e "1\t1172783\t.\tCCTCTGTCCTGGTCGCGTTGCCCAGCG\tC\t.\t.\t."
echo -e "1\t1172784\t.\tC\tT\t.\t.\t.") | bcftools view -Oz -o in.vcf.gz
bcftools index in.vcf.gz
(echo -e "1\t1172777\t1172804"
echo -e "1\t1172806\t1172808") > in.bed
bcftools view -R in.bed -Oz -o out.vcf.gz in.vcf.gz
bcftools index out.vcf.gz

[E::hts_idx_push] unsorted positions
[E::main_vcfindex] tbx_index_build failed for out.vcf.gz

**Comment by FrankFeng** [comment]
Maybe you can try --targets-file instead of --regions-file? Please see the documentation.

**Comment by freeseek** [comment]
Yes, that would solve the issue. But is it really considered okay that bcftools can create an un-indexable VCF file? Maybe the --regions-file option should be removed?

**Comment by tommycarstensen** [comment]
I have the same problem.

**Comment by MatthewPorterGN** [comment]
I am encountering this issue as well: Two years later --regions-file in bcftools v1.5 produces an unsorted VCF from a sorted VCF file. These unsorted entries are actually duplicate entries which I can successfully remove by running vcf-sort followed by piping to 'uniq'.

**Comment by garrett-stevens** [comment]
I'd like to chime in here and add my vote to the case for fixing the `--regions-file` option instead of just using `--targets-file`. As the docs indicate, they really aren't the same:
>  ...-r checks both start and end positions of indels, whereas -t checks start positions only

This difference can be important sometimes. Here's a simulated observed vs. reference sequence with a deletion and a bed region spanning the end of the deletion:
```
                   |--------deletion--------|
Observed seq:  CCTC                          CCGTGG
Reference seq: CCTCTGTCACAGGCTTACCCTCCGTATTCACCGTGG
                     ^   |------bed region-------|
        position 10000
```
Here's the corresponding VCF and BED files:
`in.vcf.gz`
```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=1,length=249250621,assembly=b37>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
1	9997	CTGTCACAGGCTTACCCTCCGTATTCA	C	.	.	.
```
`in.bed`
```
1	10003	10028
```
Output of `bcftools view --no-version --regions-file in.bed in.vcf.gz`
```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=1,length=249250621,assembly=b37>
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
1	9997	.	CTGTCACAGGCTTACCCTCCGTATTCA	C	.	.	.
```
Output of `bcftools view --no-version --targets-file in.bed in.vcf.gz`
```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=1,length=249250621,assembly=b37>
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
```
I'd really rather use `--regions-file` because `--targets-file` can miss these types of deletions, but it's hard because of the problem of duplicate variants getting pulled. I would hazard a guess that the duplicate variants come from the fact that `--regions-file` will pull a deletion multiple times if it is overlapped by multiple BED regions, but I'm not sure what the fix would be for that.

Thanks.

**Comment by samuelandjw** [comment]
I just encountered this problem in bcftools 1.9. Hope fix come soon.

**Comment by pd3** [comment]
This is a difficult probem to solve at bcftools level. There are multiple workarounds:
1) give both `--regions-file regs.txt --targets-file regs.txt`
2) fix regs.txt to remove overlaps `sort -k1,1d -k2,2n -k3,3n | bedtools merge`

**Comment by samuelandjw** [comment]
> This is a difficult probem to solve at bcftools level. There are multiple workarounds:
> 
>     1. give both `--regions-file regs.txt --targets-file regs.txt`
Could you explain how using both -R and -T works? How is it different from using only -T?

**Comment by pd3** [comment]
Uh, ignore me there. It depends on the exact situation and is not a general solution, helps only with one type of problem. The `-R` uses index to jump to the region of interest and pulls in also overlapping records with starting coordinate outside the region. These can be removed by simultaneously providing `-T`. However, your problem is probably overlapping regions. Merging the intervals should do the trick.

**Comment by pd3** [comment]
Hopefully this should be fixed by https://github.com/samtools/htslib/commit/db90fb58b06d6f3b27b5b873588da7c77844da22. Can you please try it out?
