### ISSUE TITLE
norm --remove-duplicates should keep the --old-rec-tag INFO field 

### ISSUE THREAD

**Issue by davmlaw** [samtools/bcftools#2225]
If you use bcftools norm with ```--old-rec-tag``` but without ```--remove-duplicates``` the INFO tag is written so you can capture that the variant was normalized:

```
NC_000004.12	169002212	.	CA	C	.	.	.
NC_000004.12	169002212	.	CAAAAA	C	.	.	.
NC_000004.12	169002212	.	CAAAAAAAA	C	.	.	.
NC_000004.12	169002212	.	CAAAAA	C	.	.	BCFTOOLS_OLD_VARIANT=NC_000004.12|169002212|CAAAAAAAA|CAAA
```

However if you ran this with ```--remove-duplicates``` then it removes the INFO field:

```
NC_000004.12	169002212	.	CA	C	.	.	.
NC_000004.12	169002212	.	CAAAAA	C	.	.	.
NC_000004.12	169002212	.	CAAAAAAAA	C	.	.	.
```

So you don't know what happened to your variant.

In an idea world, you'd have some kind of way of merging the INFO fields in an rmdup, but failing that I know the "take the 1st record and throw away any later ones" is how it would work if you applied norm then rmdup in 2 separate operations - however as this is all 1 command line operation, it kind of seems like the ```--old-rec-tag``` INFO field should be there 

Command line:

```
bcftools norm --multiallelics=- --rm-dup=exact --check-ref=w --old-rec-tag=BCFTOOLS_OLD_VARIANT --fasta-ref=/data/annotation/fasta/GCF_000001405.39_GRCh38.p13_genomic.fna.gz -
```

```
d$ bcftools --version
bcftools 1.20
Using htslib 1.20
```

**Comment by pd3** [comment]
This is an interesting case. If we think abou it, technically, the removed record is the one that was normalized. The one that remained was left untouched. If the two records came in the reverse order, the information would be preserved.

I am afraid there is not much that can be done about it. We cannot simply transfer all tags from the removed record to the one we keep, because such operation is not defined well: What if there are multiple records that were removed, which one is the main one? What if there are conflicting tags? 

I can see a potential for a tool with a more complex logic which transfers tags "vertically" in between duplicate records. Unfortunately, this is not something I'd have the capacity to do, and don't have a strong motivation for it. Sorry!
