### ISSUE TITLE
bcftools merge irregularly creates negative AD values when alt alleles don't match between files

### ISSUE THREAD

**Issue by happ-m** [samtools/bcftools#2244]
In trying to merge 2+ vcf files output from bcftools call where the goal is to genotype a fixed list of positions, I have ran into a handful of negative allelic depth values in the output. In trying to narrow down the root cause, it appears as though this happens if the alternate allele is not the same across files. Including when there is no alternate allele in one file but it is present in another. 

The behavior also appears to be very inconsistent in a couple of ways. 

1) sometimes it replaces the initial GT call for that sample to ./.
2) in trying to create some small example files to provide, one of the positions I had identified as problematic in the larger dataset no longer generated negative values when merging using the subsetted data.

You will find two small datasets ( A & B) that when merged, create negative AD values at variant position 1:6070233.

Happy to provide larger datasets privately that captures the range of issues I am seeing. I am using v1.2.0

[A.vcf.gz](https://github.com/user-attachments/files/16501917/A.vcf.gz)
[B.vcf.gz](https://github.com/user-attachments/files/16501918/B.vcf.gz)
[Merged.vcf.gz](https://github.com/user-attachments/files/16501919/Merged.vcf.gz)

**Comment by happ-m** [comment]
Thanks! I will go back to that version for the time being.

**Comment by pd3** [comment]
I believe this is now fixed by https://github.com/samtools/bcftools/commit/ab40ca7da9cfb4bcce165e05107ee918cda45624.

The bug affected tags with Number=R and Number=A values. For example, rows with high-coverage
FORMAT/AD values (bigger or equal to 128) would have been assigned to incorrect samples in
the manner of skipping every other value in the input file and filling in gibberish for the
rest.

The problem was introduced by extending support to 32-bit ARM machines and big-endian platforms.  

Please test this quick fix thoroughly and let us know if you observe anything odd.

**Comment by happ-m** [comment]
Thank you! Just tested on a couple dozen different full size files I was working with and so far things seem to look normal.
