### ISSUE TITLE
write-index does not appear to work from concat command

### ISSUE THREAD

**Issue by ASLeonard** [samtools/bcftools#2246]
I was concatting 29 uncompressed vcfs and indexing the output
```
bcftools concat -o autosomes.vcf.gz --write-index {1..29}.vcf
```

However, the resultant index is more or less empty, and running `bcftools index -n autosomes.vcf.gz` returns 0.
Deleting that index and re-indexing (either via `tabix -p vcf` or `bcftools index`) produces a larger index that returns the correct number of variants from the previous command.

This seems to also occur if the input to concat is compressed, or with `--write-index=tbi`, so seems to be general issue rather than a specific combination of events.

This is with 
```
bcftools 1.20-45-g5e7ea8a0-dirty
Using htslib 1.20-54-gfbe5ff6c-dirty
```

Best,
Alex

**Comment by whitwham** [comment]
I see what it is doing.  In this case it is writing out the VCF in the simplest way (`vcf_write_line`) which is good for speed but does not contain any index writing code.  So all that is produced is the index header with no actual index.

I will look at making it work.

**Comment by thierrygrange** [comment]
I have indeed observed the same problem with bcftools 1.20. It took me a while to figure out the problem and to find out that it was notified already here. The last current version is 1.21 dating from September 12th. This seems a little earlier than the comments indicating that the problem was solved and there is no indication in the description of the changes affecting version 1.21 that this issue with --write index was solved. Is version 1.21 solving the issue and should I reinstall bcftools 1.21 or wait for 1.22 and add a command with bcftools index meanwhile in my pipeline?
