### ISSUE TITLE
[OS X] plugins are built as shared libraries but should be bundles

### ISSUE THREAD

**Issue by nieder** [samtools/bcftools#225]
Mach-O makes a distinction between shared linked libraries and loadable modules.  For gcc and clang on OS X, the compiler flag is `-bundle` (instead of `-shared`). I don't think gcc on Linux has a comparable flag.

**Comment by jmarshall** [comment]
Indeed, we could build the plugins on OS X with `-bundle -bundle_loader bcftools` and I see that dlopen() and friends remain the right way to open them at runtime.

So that's probably worth doing.  However: what does it actually buy us?

(We wouldn't have LC_ID_DYLIB library versioning to fill out.  What other differences are there?)

**Comment by nieder** [comment]
From a performance point of view, I don't know if there's any difference in whether a binary dlopens() a bundle or a library. While both can be used via dlopen(), but AFAIK libraries can't be unloaded.

From a packaging point of view (how I found this), bundles are treated as normal files (because they lack versioning), while libraries need to be tracked since OS X uses the full install_name when linking to them.
