### ISSUE TITLE
'annotate' error message when trying to put a Float into an 'Number=A,type=Integer' INFO

### ISSUE THREAD

**Issue by Gullumluvl** [samtools/bcftools#2306]
Dear maintainers,

minor problem, but the error message is misleading in the following situation, because it says:

    Incorrect number of values (2) for the newTAG tag at chr1:144

Ideally it should say `Incorrect type for the newTAG tag` or similar message.

##### BCFtools version:

    bcftools 1.21-38-g4f8bf53
    Using htslib 1.21-11-g3c90481

##### Steps to reproduce:

```bash
echo -e '##fileformat=VCFv4.2
##contig=<ID=chr1,length=100000000>
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype call">
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tsampleA\tsampleB
chr1\t144\tchr1:144:SG\tA\tG\t135\tPASS\t\tGT\t0/0\t0/1' > test.vcf

echo '##INFO=<ID=newTAG,Number=A,Type=Integer,Description="New tag">' > newTAG.hdr

echo -e 'chr1\t144\t0.002457' | bgzip > annot.tab.gz
tabix -s1 -b2 -e2 annot.tab.gz

bcftools annotate -h newTAG.hdr -a annot.tab.gz -c 'CHROM,POS,INFO/newTAG' -Ob -o out.bcf test.vcf
```

Also, when the header line for `newTAG` has `Number=1` instead, there is no error but the tag is set to `0,2457` in this example. Is it expected?

Best

**Comment by pd3** [comment]
Thank you for the bug report.

The tags declared as Number=R,A need to be given also the REF,ALT alleles via `-c`, otherwise the program would not be able to match the values to the correct allele. This is now made more strict and the program will throw an error if REF,ALT is not given.

Regarding the other problem, the parsing was made more strict so that parsing a float (0.002457) into a Type=Integer tag will throw an error.
