### ISSUE TITLE
Documentation for the output of bcftools stats

### ISSUE THREAD

**Issue by jamesblackshaw** [samtools/bcftools#316]
I have been using bcftools stats, but I’m uncertain about what several fields in the output mean. The documentation is good for what the command line options do, but I cannot findbreakdown of what the output means or how it is calculated. it would help to have a breakdown of what each data type in the output means.

This is  part of the output from vcftools stats on my file:
# SN, Summary numbers:
# SN    [2]id   [3]key  [4]value

SN      0       number of samples:      4301
SN      0       number of records:      803
SN      0       number of SNPs: 714
SN      0       number of MNPs: 0
SN      0       number of indels:       94
SN      0       number of others:       7
SN      0       number of multiallelic sites:   33
SN      0       number of multiallelic SNP sites:       2

Things I can't find in the documentation:
-Does “multiallelic” denote “more than 2 alleles” rather than “not monomorphic”?
-The number of SNPS+indels+others does not sum to the total number of records. Is this because an SNP can also be an indel or “other?”
-What types of variants are covered by “others” here?
-Why is the id[2] field blank for all sections of my output?

**Comment by mcshane** [comment]
* Does “multiallelic” denote “more than 2 alleles” rather than “not monomorphic”?

Yes. 2 or more alternate alleles at a site.

* The number of SNPS+indels+others does not sum to the total number of records. Is this because an SNP can also be an indel or “other?”

A mutilallelic site may contain both a SNP and an indel for instance and hence will contribute a count to both tallies.

* What types of variants are covered by “others” here?

complex substitutions, SVs, complex rearrangements. Basically anything not a SNP, insertion/deletion (unless represented by a symbolic allele) or MNP.

* Why is the id[2] field blank for all sections of my output?

`id` field is relevant when comparing two files with bcftools stats. `id` will then be 0,1 or 2 and will represent sites unique to the first file, sites unique to the second file and sites common to both.

**Comment by powelleric** [comment]
I, too, am having an extremely difficult time making sense of the fact that the "number of records" does not equal the sum of SNPs+MNP+indels+others.

According to @mcshane, this is because multi-allelic sites are being counted twice.  Referring to the source code of `do_vcf_stats()` in `vcfstats.c`, we see the following code block:

```
        int line_type = bcf_get_variant_types(line);
        init_iaf(args, reader);

        stats_t *stats = &args->stats[ret-1];
        if ( args->split_by_id && line->d.id[0]=='.' && !line->d.id[1] )
            stats = &args->stats[1];

        stats->n_records++;

        if ( line_type==VCF_REF )
            stats->n_noalts++;
        if ( line_type&VCF_SNP )
            do_snp_stats(args, stats, reader);
        if ( line_type&VCF_INDEL )
            do_indel_stats(args, stats, reader);
        if ( line_type&VCF_MNP )
            do_mnp_stats(args, stats, reader);
        if ( line_type&VCF_OTHER )
            do_other_stats(args, stats, reader);

        if ( line->n_allele>2 )
        {
            stats->n_mals++;
            if ( line_type == VCF_SNP ) stats->n_snp_mals++;
        }
```
If @mcshane is correct, then that block of code would run once for each allele in a vcf record - not necessarily once for each record.  This begs further questions then.  

First of all, the "number of records" calculation is now very confusing because it no longer refers to the number of actual vcf records but the number of alleles observed in the VCF.  
```
stats->n_records++;
```

Second, the count of multi-allelic sites itself has been doubled because that, too, was incremented for each allele.  

```
if ( line->n_allele>2 )
        {
            stats->n_mals++
```
In summary, it would seem that each multi-allelic site counts twice (+2) towards the number of records and twice (+2) towards the number of multi-allelic sites.

Please be aware that I do not have any experience with the bcftools source other than what I have dug through for this issue.  I could very well be wrong in my interpretation.  However, prior to posting this I looked for tests that would validate the functionality of `bcftools stats`.  All I found was `test/stats.B.chk` and `test/stats.chk`.  Both tests consist simply of 4 snps.  No indels, others, MNP or otherwise.

If this is in fact the only testing, I propose a more thorough test dataset be developed that will cover all the possibilities.  Furthermore, that test set should be used to improve the documentation and clarify this issue once and for all.  **Specifically, the test set should clearly show how a multi-allelic site contributes to counts of both SNPS and indels, and thus accounts for the fact that the totals do not add up the way OP (and others) expect.**

Please note that this exact issue has been posted on various forums multiple times over the years.  It is a straightforward issue that should be resolved once and for all.

**Comment by pd3** [comment]
Yes, it would be good to resolve this. Would you like to contribute a pull request with more complete test cases and possibly a fix too? That would be much appreciated.

**Comment by powelleric** [comment]
I'm afraid I'm probably a bit too busy right now.  I've moved on to vcflib for my stats but if I recall the output from bcftools was actually more informative than vcflib (so would be good to have it fixed).

I will let you know if I find time to undertake the test cases and/or bug fixes.

p.s. Another thing I noticed is that the information reported by the perl library contained a number of differences from bcftools even though the documentation makes it sound like they are comparable.  I'm talking about differences in basic counts (not any complex statistics) so that is another indication that something may be off in the stats calculation.

**Comment by pd3** [comment]
I verified that the program behaves as expected and its output is in fact quite intuitive. For example, if there is a record with both a SNP and an indel, both SNP and indel counters will be incremented.

Just pushed a commit which adds a description of these fields to the output. Please let me know in case of problems. Thanks for reporting the issue.

**Comment by powelleric** [comment]
@pd3 Glad to know that everything is working as expected.  I will have a look at the descriptions in the new commit. Thanks a bunch for looking into this.

**Comment by garrett-stevens** [comment]
Hi, sorry to jump in here but I wanted to clarify something for myself. In the new commit comments, it says that "number of SNPs" is the number of rows with a SNP. So that means that a VCF line like this one:
```
1	1006	.	C	G,T	.	PASS	.	GT	0/0	1/1	2/2
```
only increases the SNP counter by one?

Thanks.

**Comment by pd3** [comment]
Yes. Also increments the counters "number of multiallelic sites" and "number of multiallelic SNP sites"

**Comment by EasperOne** [comment]
Hi, hope you're doing good. I would love to ask whether my bcftools stats output is correct. Because it seems to me that 100% variants are SNPs (number of records = number of SNPs). However, the number of multiallelic sites does not concur with multiallelic SNP sites. So, I'm not sure what is the source of discrepancy here... Can anyone help me?
```
# SN, Summary numbers
# SN	[2]id	[3]key	[4]value
SN	0	number of samples:	250
SN	0	number of records:	15802416
SN	0	number of no-ALTs:	0
SN	0	number of SNPs:	15802416
SN	0	number of MNPs:	0
SN	0	number of indels:	0
SN	0	number of others:	0
SN	0	number of multiallelic sites:	138429
SN	0	number of multiallelic SNP sites:	59140
```
