### ISSUE TITLE
handling of indices

### ISSUE THREAD

**Issue by danielecook** [samtools/bcftools#358]
Hello - I'd like to make a suggestion regarding indices. There are a lot of directions that one could go, but my main issue is that because indices are much smaller than the vcf files they are frequently transferred first and as a result are 'newer' than the vcf files themselves. This results in me perpetually observing the warning message regarding index files. 

What about one of the following remedies:

1.) Storing the index at the end of the VCF file.
2.) Using a hash to validate an index file

**Comment by wkretzsch** [comment]
I have the same problem with index files.  

However, I'm not sure I want to pay the hashing penalty every time I use a BCF/VCF.  Most of my files are gigabytes in size.

How about making a hash check part of `bcftools index` with a new flag (let's say `-h`).  In this mode bcftools first performs a hash check against the index.  If the hash matches, then the index is just touched instead of being rebuilt.  `-h` would probably imply `--force`.  Without `--force` I would expect bcftools to just check the hash and make sure it matches the BCF/VCF.

**Comment by pd3** [comment]
Hi,
adding the index to the end of the VCF is not going to have much support I am afraid.
If you are sure the index is OK, you can simply `touch` the index file. 
If you'd like to verify the integrity of the index, you need to traverse the whole data file anyway, so you may as well reindex.

**Comment by wkretzsch** [comment]
But isn't a straight up hash of a file much faster than indexing a gzipped VCF?  On RAID systems I've seen md5sums read at 600 MB/s, whereas parsing a VCF through bcftools is generally considered slow.

**Comment by pd3** [comment]
Sorry, I was not reading properly. Yes, storing md5 in the index file would help and would be much faster.

**Comment by wkretzsch** [comment]
I think that's a minimal improvement that everybody could get behind?

**Comment by pd3** [comment]
This question is better suited for hts-specs, closing here.
