### ISSUE TITLE
bcftools: vcfannotate.c:1520: buffer_annot_lines: Assertion `args->alt_idx < tmp->ncols' failed.

### ISSUE THREAD

**Issue by freeseek** [samtools/bcftools#365]
The following code:

(echo "##fileformat=VCFv4.1"
echo "##contig=\<ID=22,length=51304566\>"
echo -e "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO"
echo -e "22\t51156292\t.\tA\tG\t.\t.\t.") > a.vcf
echo -e "22\t51156251\t51156493\tA" | bgzip > b.tsv.gz
tabix -s 1 -f -b 2 -e 3 b.tsv.gz
echo "##INFO=\<ID=X,Number=1,Type=String,Description=\"xxx\"\>" \> b.hdr
bcftools annotate a.vcf -a b.tsv.gz -h b.hdr -c CHROM,FROM,TO,REF,ALT,X

Causes bcftools to segfault with the following output:
bcftools: vcfannotate.c:1520: buffer_annot_lines: Assertion `args->alt_idx < tmp->ncols' failed.

I am not sure what is going on here. When using large annotation tables and large in.vcf.gz files, the error is triggered only at the end of the annotations, usually leaving a large output with the last few lines truncated.

The problem is reproducible with the latest version of bcftools:
Version: 1.2-190-g71921ca (using htslib 1.2.1-259-gbbd3334)

**Comment by pd3** [comment]
Hi,
thank you for the test case. Technically, it is not a segfault but an error thrown by the program. It was caused by an incorrect number of fields in the b.tsv.gz file: the last line has only 4 fields but 6 should be present. Hopefully the improved error message will help to identify the problem next time https://github.com/pd3/bcftools/commit/77ae31d340ba52ee80ef8b0e21f1bc6987877a15
Thanks

**Comment by freeseek** [comment]
Great, thank you pd3. I think it the sort of makes sense as to why the error would arise only at the last row. I am a bit worried that the previous behavior would have caused unintended consequences, as even if the error was generated, most of the output VCF file was created, possibly with inconsistent annotations. An improved error message will really make a difference here.
