### ISSUE TITLE
bcftools annotate fails to parse INFO fields missing in a header

### ISSUE THREAD

**Issue by gtamazian** [samtools/bcftools#431]
_bcftools annotate_ fails to process a VCF file which has INFO fields missing in its header. For the attached MWE ([mwe.vcf](https://github.com/samtools/bcftools/files/288522/mwe.vcf.gz)), it shows the following output

```
[W::vcf_parse] INFO 'dbSNP138_ID' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'dbSNP142_ID' is not defined in the header, assuming Type=String
Encountered error, cannot proceed. Please check the error output above.
```

being launched as

```
bcftools annotate -x ID mwe.vcf
```

After adding the following two lines to the header

```
##INFO=<ID=dbSNP138_ID,Type=String>
##INFO=<ID=dbSNP142_ID,Type=String>
```

the tool correctly processes the fixed file [mwe_fixed.vcf.gz](https://github.com/samtools/bcftools/files/288523/mwe_fixed.vcf).

**Comment by pd3** [comment]
This is a known recurring problem. Although VCF specification allows undefined tags, htslib treats VCFs internally as BCFs, where all tags must be defined in the header - this is because of the way BCF is designed (and we prefer BCF over VCF for its speed).

We work around this problem by adding missing definitions on the fly. This is OK for read-only operations but it leads to problems when writing. In this particular case, the reader encounters the undefined dbSNP* tags, updates its header structures and continues reading. The writer, however, does not know about the new tag (it keeps a separate output header) and thus cannot write it out.

Although it is possible in principle to hack the code to handle such situations, it would be quite hacky given the available alternative: the user can easily fix the header using `bcftools reheader`.

**Comment by gtamazian** [comment]
Thanks for the explanation, I agree that using `bcftools header` is the easiest option.

I suppose that a more detailed message would be useful if a user tries to write a VCF file with fields missing from its header. For example (the third line):
```
[W::vcf_parse] INFO 'dbSNP138_ID' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'dbSNP142_ID' is not defined in the header, assuming Type=String
Cannot write a VCF file with columns missing in its header; please use bcftools reheader to fix the header.
Encountered error, cannot proceed. Please check the error output above.```
