### ISSUE TITLE
Sites.txt output from isec is not in VCF format

### ISSUE THREAD

**Issue by tantrev** [samtools/bcftools#495]
It'd just be nice if the output from bcftools' "isec" mirrored the output from "vcf-isec" - that is, being in the VCF format.

In my current use case, I'm trying to filter out shared variants from individual VCF files and it'd be great to take advantage of bcftools' faster speed.  Thank you in advance.

**Comment by pd3** [comment]
By default the program prints only list of sites. For VCF, also the `-w` option must be given.

**Comment by tantrev** [comment]
I'm probably missing something obvious but I can't seem to figure to figure this out.  When I run without "-w", for example:

`cat files.txt | xargs bcftools isec --nfiles 1 -c all`

bcftools returns 118 variants.  But when I run with "-w 27" (I think that's the right notation? I have 27 files), bcftools only returns 6 variants:

`cat files.txt | xargs bcftools isec --nfiles 1 -c all -w 27`

Am I just missing something painfully blatant?

**Comment by pd3** [comment]
The `xargs` command should not be used with `bcftools isec` this way, because it is not guaranteed to execute the argument only once. If the paths were too long or if the files were too many, the program might be executed multiple times, each time with a different set of files.

The `-w` option expects a list of file indexes. So `-w 27` tells the program to print records from the 27th file only. 

Unlike `vcf-isec`, this new version is designed more carefully and does not allow to mix records from different VCF files, this led to all sort of troubles. If it does not matter, you can use the `bcftools isec -p` and then concat the files using `bcftools concat -aD`.
