### ISSUE TITLE
@#### in output from `bcftools csq`

### ISSUE THREAD

**Issue by brentp** [samtools/bcftools#522]
using `ftp://ftp.ensembl.org/pub/grch37/release-84/gff3/homo_sapiens/Homo_sapiens.GRCh37.82.chr.gff3.gz`

and the attached `oo.vcf.gz` file with the command:
```
./bcftools csq -p a -g Homo_sapiens.GRCh37.82.chr.gff3.gz -f /data/human/human_g1k_v37.fasta oo.vcf.gz > vv.vcf
```
there are several cases in the VCF where the BCSQ in the INFO has a BCSQ like: `;BCSQ=@874816`

[oo.vcf.gz](https://github.com/samtools/bcftools/files/625886/oo.vcf.gz)

cc @pd3 and @mcshane

**Comment by mcshane** [comment]
This is because the consequences are for variants across multiple positions. Think of it as a pointer to the position where the consequence annotation is stored for the haplotype consisting of the combined variants at 1:874816 and 1:877831.

Have a look at the examples in man page (http://samtools.github.io/bcftools/bcftools.html#csq) and let us know if this is unclear.

**Comment by brentp** [comment]
shoot. I didn't see the docs. Thanks for the pointer.

marginally related, but is there a way for to have unphased data be treated a single variant at a time?
I know the strength of the tools is the consequence of the haplotype, but we often have unphased data. Maybe I'm not understanding all the possible options to `--phase`

**Comment by pd3** [comment]
I see the documentation on the web is not the latest. There is also the `-p R` option which creates non-reference haplotypes if possible, for example `0/1 -> 1|1`, `1/2 -> 1|2`

**Comment by brentp** [comment]
I also found the `--local-csq` flag. Thanks guys. This is awesome.
