### ISSUE TITLE
Incorrect error message from mpileup

### ISSUE THREAD

**Issue by jkbonfield** [samtools/bcftools#571]
mpileup wants a reference and suggests I use the ```--reference``` option, but it doesn't have this as a long option, so I need ```-f``` instead.

```
@ deskpro[samtools.../bcftools]; ./bcftools mpileup ~/scratch/data/9827_2#49.1m.bam
Error: mpileup requires the --reference option by default; use --no-reference to run without a fasta reference
@ deskpro[samtools.../bcftools]; ./bcftools mpileup --reference $HREF ~/scratch/data/9827_2#49.1m.bam
mpileup: unrecognized option '--reference'
Invalid option: '?'
```

**Comment by ahmedrahat** [comment]
Were you able to resolve the "mpileup: unrecognized option" error?

**Comment by pd3** [comment]
This was just a cosmetic issue, the error message suggested using the option in a form which was not available. This has been fixed long time ago and the error message now correctly poionts to `--fasta-ref`.

I suspect your problem is different. Type `bcftools mpileup` for the list of options supported in the version you are running.

**Comment by ahmedrahat** [comment]
Your issue ended up being different from mine but the main error was the mpileup: unrecognized option. I ended up installing the newest version as the previous one did not detect the option because it wasn't available. Thanks for the help.
