### ISSUE TITLE
bcftools view -m3 -C 0:minor

### ISSUE THREAD

**Issue by tommycarstensen** [samtools/bcftools#575]
I'm looking for triallelic records, for which the allele count of one of the alleles is zero. I'm doing `bcftools view --min-alleles 3 --max-ac 0:minor $vcf`, but that prints all records. For example this one:

```
20	61279	rs189899941	C	A,T	.	PASS	AR2=0.884;DR2=0.907;AF=0.009,0.066;AC=26,297;AN=4596
```

It works fine, for `--max-ac $i:minor`, when `$i` is greater than zero. Is this a bug or just unexpected behaviour? Thanks!

**Comment by pd3** [comment]
It is a bug, now fixed by 5e4965916cc26ec33184dcf212aeb16eab211606.

However, the command would not do what you want, because both alternate alleles would have to be zero. If you want to print records with at least one alternate count equal zero, you can use the `-i/-e` options:

    bcftools query -f'%AC\n' -i'N_ALT==2 && AC[*]==0'

In this example it's shown for `query` but works equally with `view`.
