### ISSUE TITLE
bcftools call core dumped

### ISSUE THREAD

**Issue by yassineS** [samtools/bcftools#663]
```
[mpileup] 1 samples in 1 input files
<mpileup> Set max per-file depth to 8000
bcftools: mcall.c:1246: mcall_trim_numberR: Assertion `nret==nals*nsmpl' failed.
20599 Broken pipe             samtools mpileup -u -B -q20 -Q20 -l $TARGET -f $REF -R -t DP,AD,ADF,ADR,SP,INFO/AD,INFO/ADF,INFO/ADR <in.bam>
     20600 Aborted                 (core dumped) | bcftools call -O z -o <out.vcf.gz> -T als.tsv.gz -C alleles -A -V indels -v -m
```

**Comment by pd3** [comment]
Any chance you could narrow the problem down and create a small test case?

**Comment by yassineS** [comment]
A smaller bam file or target? The bam file I am trying is fairly small.

**Comment by pd3** [comment]
Something that we could play with and reproduce the problem. For example you could save the output of the first command (`samtools mpileup`) and then see find the record that breaks the second command (`bcftools call`). 

You might want first to check with the latest version and use `bcftools mpileup ... | bcftools call`, so that you are sure that different versions of samtools/bcftools are not mixed.

**Comment by JohnMCMa** [comment]
Hi @pd3 ,

I have a similar issue and I can provide the input file in question. How do I send it?

**Comment by JohnMCMa** [comment]
Hi @yassineS : Can you try doing the same operation with bcftools above 1.10? When I was trying to generate a minimum example, I noticed the issue occurs in bcftools 1.9.0, but disappears in 1.10.2. Since there has been a lot of fixes on htslib at 1.10.0, I suspect it also fixed the bug behind this failed assertion.

**Comment by yassineS** [comment]
An update solved my issue. I can't reproduce the error above.

**Comment by pd3** [comment]
Glad to see the problem disappeared, closing the issue now.
