### ISSUE TITLE
Bcftools norm documentation is incorrect.

### ISSUE THREAD

**Issue by jkbonfield** [samtools/bcftools#674]
1. It states "all" is a valid argument to -d, but it doesn't accept this.  I think it means to state "all".

2. It claims -d requires "-a, --allow-overlaps", but this is not a valid option.

I'm also struggling to explain why it normalises as it does, but that's a completely different issue I guess.

Input:

```
20	226085	.	TATATATATATATATATATATATATATATA	TATATATATATATATATATATATATATA	125	.	INDEL;IDV=38;IMF=1;DP=38;VDB=0.428039;SGB=-0.662043;MQSB=0.924584;MQ0F=0;AC=2;AN=2;DP4=0,0,6,3;MQ=60	GT:PL	1/1:155,27,0
```

Output with norm -f $HREF:

```
20	226084	.	GTA	G	125	.	INDEL;IDV=38;IMF=1;DP=38;VDB=0.428039;SGB=-0.662043;MQSB=0.924584;MQ0F=0;AC=2;AN=2;DP4=0,0,6,3;MQ=60	GT:PL	1/1:155,27,0
20	226084	.	GTATATATA	G	222	.	INDEL;IDV=13;IMF=0.371429;DP=35;VDB=0.12089;SGB=-0.680642;MQSB=0.97584;MQ0F=0;ICB=1;HOB=0.5;AC=1;AN=2;DP4=7,3,9,3;MQ=59	GT:PL	0/1:255,0,220
```

Using `-d both` does nothing here.  I can use `-m +both` to merge into a single line, but I cannot remove the duplicate.    Why did it generate two lines when there was only 1 before though? The alignments show some reads with a single TA copy added and others with 3 TA copies removed. Is it 2 lines because the reference is essentially third allele here?

**Comment by pd3** [comment]
Ah, it seems the documentation is out of date, thanks for reporting. The usage text displayed should be up to date. 

The example is curious. Could you point me to the file so that I can check? Most likely there are two records in the original VCF with different coordinates that are normalized to the same position. 

The algorithm used for normalization is described here http://genome.sph.umich.edu/wiki/Variant_Normalization

**Comment by pd3** [comment]
Thanks for the offline copy of the files. To confirm, the duplicate lines were created by two realigned records. Originally the `-d` option worked only on input records, this has been now extended to for output records.

**Comment by jkbonfield** [comment]
Thanks Petr.
