### ISSUE TITLE
bcftools +fill-tags tag"MAF" is not supported

### ISSUE THREAD

**Issue by michellekee** [samtools/bcftools#703]
Hi,

I was trying to add the MAF tags with the command
`bcftools +fill-tags -- -t MAF > $PREFIX.vcf`

 into my output from Sanger imputation but the following error msg occurred: 

> Error parsing "--tags MAF": the tag "MAF" is not supported

I had a warning that the index file is older than the data file, but it was downloaded from Sanger Imputation Service directly. Could this be the problem?

Any solutions advised would be very much appreciated!

Thank you!

**Comment by pd3** [comment]
It works for me. Is it possible that you are using an older version of the plugin? The latest can be found here
https://github.com/samtools/bcftools/blob/develop/plugins/fill-tags.c

The warning about the index is not generated by the plugin but from a command upstream. To fix it, either re-index the file, or if you are certain it is up to date, run `touch <index-file>`. It does not matter for the issue here.

**Comment by pd3** [comment]
I'll assume that the problem was in using an older version and that the upgrade helped. Closing the issue, please reopen if still not resolved.
