### ISSUE TITLE
bcftools reheader missing --threads option

### ISSUE THREAD

**Issue by freeseek** [samtools/bcftools#722]
I have just realized that the following command:
```bcftools view --threads 2 --no-version -Ou input.bcf | bcftools reheader -s samples | bcftools view --threads 2 --no-version -Ob -o output.bcf```
Runs much faster than this other command:
```bcftools reheader -s samples input.bcf -o output.bcf```
I believe the issue here is that `bcftools reheader` is missing the "--threads" option. Maybe a warning could be included that (de)compression with `bcftools reheader` cannot be parallelized. It was not even clear to me in the beginning that re-header-ing requires compression and decompression. :-(

**Comment by jkbonfield** [comment]
I was the one who added various more threading options, after adding multi-threaded decoding.  I guess I didn't do reheader because I'd assumed, like you, that it did not require decompression and compression steps.

It seems to imply the primary purpose is to change sample names, with options to supply and old->new map.  This scenario shouldn't require recompression at all.  Changing the order of header lines could require this, but it's unlikely the code spots and handles this case.

After manipulating the header it looks to end with this:

```
    while (1)
    {
        nread = bgzf_raw_read(fp, buf, page_size);
        if ( nread<=0 ) break;

        int count = bgzf_raw_write(bgzf_out, buf, nread);
        if (count != nread) error("Write failed, wrote %d instead of %d bytes.\n", count,(int)nread);
    }
```

The raw vcf.gz functions are just straight hread/hwrites and perform no (de)compression.  This should be fast.  Keeping data in vcf.gz is the easy workaround for now (although it'll slow things down elsewhere).

However when given *bcf* it looks to just do a read/write loop.  It has a lot of sanity checking options which require the data to be uncompressed.  Over to you Petr.

**Comment by pd3** [comment]
Hi, sorry about the delay. James is correct. To clarify, sample reordering is considered *renaming*, therefore only header is modified. (There should be no reason really to reorder columns in the whole file.)

The support for BCF threading has been now added.
