### ISSUE TITLE
Problem converting vcf to hap/legend/sample 

### ISSUE THREAD

**Issue by sboer** [samtools/bcftools#730]
Hi!

I have tried to convert a vcf.gz-file to hap/legend/sample-format with bcftools, but the output file looks strange. 

I have reference panel from 1000G with mitochondrial markers; the vcf-file looks like this:
![image](https://user-images.githubusercontent.com/35312839/34796524-c4ddee7a-f623-11e7-99a3-4b6d193c894f.png)

, which should be the correct format for haploid markers. 

I have tried to convert to hap/legend/sample format (required by IMPUTE2) by running:

bcftools convert --haplegendsample RefPanel--vcf-ids ALL.chrMT.phase3....vcf.gz

The resulting .legend.gz and .sample-files look ok, but the .hap.gz-file does not look right:
![image](https://user-images.githubusercontent.com/35312839/34797139-7347ace8-f625-11e7-9452-2011600447bb.png)

From what I have understood (according to the SHAPEIT and IMPUTE manuals), the .hap-file is supposed to look like this:

0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0
0 0 1 0 0 0 0 0 0 0 0 

(one column per sample for haploid markers)

or, like this, with two columns per sample -  the second column being a dummy for the second allele, which is not present in haploids
0 - 0 - 0 - 0 - 0 - 0 -
0 - 0 - 0 - 0 - 0 - 0 -
0 - 0 - 1 - 0 - 0 - 0 - 

The .hap file also seems to have two columns per individual, but I don´t get the column-pairs to make sense (e.g. one column is 1* and the other 0*)

I have also tried to gunzip the vcf.gz-file and pipe it into the bcftools command, and I have tried to run the --hapsample command, but the results are the same..  In addition I tried to add --haploid2diploid, but it did not change the output at all (the stars were still there, and the number of columns were the same). (I view the file with zcat, if that matters..). 

Is it something I have missed here? Is the command not compatible with haploid markers (it loooks like it should be though..)

Thanks alot for any help!

**Comment by winni2k** [comment]
Hi!
What is happening here is that `bcftools convert` is interpreting the VCF as unphased haploid alleles.  That is what the `0*` means in the output.  Obviously that makes no sense.

The interesting question is which of the two possible outputs you suggest (`0 0 0` and `0 - 0 - 0 -`) should be the output in this case.  Reading over my reference spec at [shapeit.fr](https://mathgen.stats.ox.ac.uk/genetics_software/shapeit/shapeit.html#formats), it appears that shapeit, a major user of the hap/leg/samp format, implicitly assumes that samples are diploid. 

So, the correct output should be of the format `0 - 0 - 0 -` and a warning should be raised that haploid samples are being coerced to a diploid file format. The convert command should also raise if the ploidy of the input samples is greater than two. I'll have a look about making the changes.

In the meantime you can get the `0 - 0 - 0 -` output format by changing how you store the alleles in your VCF.  You will need to replace each allele (e.g. `0`) with a diploid, phased, and half missing genotype (e.g. `0|.`). Unfortunately, the only change I can come up with is a bit involved:

```bash
# from your VCF located at input.vcf
# separate the body and header of the VCF
grep '^#' input.vcf > input.vcf.header
grep -v '^#' input.vcf input.vcf.body

# append a `|.` to all digits in the alleles section of the VCF body
cut -f10- input.vcf.body | perl -pne 's/(\d)/$1|./g' | paste <(cut -f-9 input.vcf.body) - > out.vcf.body

# combine the new vcf body with the old header
cat input.vcf.header out.vcf.body > out.vcf
```
HTH

**Comment by winni2k** [comment]
@pd3 can we mark this as a bug?

**Comment by sboer** [comment]
Thanks alot for the answer!

According to IMPUTE2, which is what I was supposed to use it for, the format can be both one and two columns, but if the two-column solution works better with SHAPE-IT, I guess that is the best way. 

I will try your code to change the vcf file meanwhile. 

Thanks!

**Comment by winni2k** [comment]
I'm digging into the code right now, and I'm not sure my suggestion will work for you.

Have you tried using the `bcftools convert --haploid2diploid` option?

**Comment by sboer** [comment]
Thanks!

I did add the --haploid2diploid option, but the result was exactly the same..

**Comment by winni2k** [comment]
Which version of bcftools are you using?  version 1.2.1 seems to work as expected.

**Comment by winni2k** [comment]
version 1.6 appears to be broken.

**Comment by sboer** [comment]
I have used version 1.5.. so there is no need to try version 1.6?

**Comment by winni2k** [comment]
Right, here are the versions I've tested:
1.6 -> broken
1.5 -> broken
1.4.1 -> broken
1.3.1 -> ok

**Comment by sboer** [comment]
I tried to modify the vcf-file, but the resulting .hap-file is now just questionmarks.. 

![image](https://user-images.githubusercontent.com/35312839/34829802-dc28ecc4-f6af-11e7-9c1f-246777d033a7.png)

The code, however, seemed to work fine:
![image](https://user-images.githubusercontent.com/35312839/34829817-eb31b35e-f6af-11e7-90ad-c7fbbf06c03b.png)


But I will try version 1.3.1 then!

**Comment by winni2k** [comment]
You should be able to get v1.3.1 from the [releases page](https://github.com/samtools/bcftools/releases)

**Comment by winni2k** [comment]
@pd3, I have tried fixing the source code, but I have run out of time [process_gt_to_hap](https://github.com/samtools/bcftools/blob/8190859b232ad1be118bf1f45490c0c0cdc0aa87/convert.c#L714).  What I have is a minimal vcf:
```
##fileformat=VCFv4.1
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##contig=<ID=X,assembly=b37,length=155270560>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	NA00001	NA00002	NA00003
X	2699450	.	A	C	.	.	.	GT	0|0	0|0	1|0
X	2699451	.	A	C	.	.	.	GT	0	0	1
X	2699968	.	A	G	.	.	.	GT	.|.	0|.	1|.
X	2699970	.	T	C	.	.	.	GT	.|0	0|.	1|.
X	2699990	.	C	<INS:ME:LINE1>	.	.	.	GT	0|0	0|0	1|0
```
which should give the haps output (of the hap/leg/samp format):
```
0 0 0 0 1 0
0* 0* 0* 1* ? ?
? ? ? ? ? ?
? ? ? ? ? ?
0 0 0 0 1 0
```

I think part of the bug is that a single allele genotype (e.g. `0`) never triggers an if statement that checks the second allele against `bcf_int8_vector_end`: https://github.com/samtools/bcftools/blob/8190859b232ad1be118bf1f45490c0c0cdc0aa87/convert.c#L778

**Comment by winni2k** [comment]
I also have a feature request: I think it's a bad idea to allow mixing of genotypes with ploidy 1 and 2 within a sample.  I think there should be a test in the convert functions for HAP/SAMPLE and HAP/LEG/SAMPLE that make sure all genotypes of a sample are of the same ploidy.

**Comment by pd3** [comment]
Thank you for reporting the bug and the test. The bug is fixed now.

**Comment by thuhongle** [comment]
Hi, I have somehow look like it is the same problem, but I am not sure. I tried to convert vcf file with unphased, diploid genotype to hap/sample/legend format, using bcftools 1.3.1 command:

bcftools convert -h chr19.out chr19.in.vcf

The vcf input file (chr19.in.vcf) looks like:
##contig=<ID=19,length=62272572>
##INFO=<ID=PR,Number=0,Type=Flag,Description="Provisional reference allele, may not be based on real reference genome">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  ACI-N   BN-N    BUF-N   F344-N  M520-N  
19      2308    .       T       G       .       .       PR      GT      0/0     0/0     0/0     0/0     0/0     
19      2310    .       C       A       .       .       PR      GT      0/0     0/0     0/0     0/0     0/0   
19      2317    .       T       G       .       .       PR      GT      0/0     0/0     0/0     0/0     0/0     
19      2324    .       T       A       .       .       PR      GT      0/0     0/0     0/0     0/0     0/0     
 
and the output hap file looks like:
1* 1* 1* 1* 1* 1* 1* 1* 1* 1*
1* 1* 1* 1* 1* 1* 1* 1* 1* 1*
1* 1* 1* 1* 1* 1* 1* 1* 1* 1*
1* 1* 1* 1* 1* 1* 1* 1* 1* 1* 

which means that bcftools thinks genotypes in my vcf file are haploid, and create * for the second allele. However, it is completely incorrect also for the first allele (should be 0 instead of 1)
My questions are:
1. How can I tell bcftools that my vcf file contains diploid genotypes?
2. Is it possible to convert directly from unphased (/) genotype to hap/sample/legend format. This is because I know the genotypes in my vcf file are phased already even though the signs are '/' instead of '|'.

What I want is the correct format for hap file, in my case should be:

0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 

It would be great if you can help! Many thanks!
THL

**Comment by pd3** [comment]
The asterisk stands for unphased genotype, so at least this part of the output is correct. The allele is of course wrong. Can you please update to the latest bcftools version? It should fix some of the issues. 

If you'd like to set all genotypes to phased, you can do so using the `setGT` plugin
````
bcftools +setGT input.vcf -- -t a -n p
````
For this, the latest github version is needed, please see installation and download instructions here http://samtools.github.io/bcftools.

**Comment by kkellysci** [comment]
For anyone who Googles across this because their compute cluster has an older version of bcftools and they're trying to find a way to work around this bug, `bcftools view -Ov $input_bcf | bcftools convert --hapsample` will get rid of the asterisks.
