### ISSUE TITLE
bcftools call multi-sample sensitivity

### ISSUE THREAD

**Issue by ju-cheng** [samtools/bcftools#811]
I have over 6000 samples and tried to do variant calling with bcftools. Seven of them are mutation positive. When I used the bam files for the individual samples, the seven mutated samples were called correctly. But when I combined all the samples into one bam file and performed variant calling, the expected variant was missed. I feel the sensitivity is compromised in the background of a large cohort. Is there anyway to keep the sensitivity for individual samples? Thanks!

**Comment by ju-cheng** [comment]
Thanks @pd3 
Tried to set --prior to 0 but did not get much success.

**Comment by pd3** [comment]
That sets it in the opposite direction, the value needs to be increased.

**Comment by ju-cheng** [comment]
Changed --prior to 1. The expected variant didn't show up. Never mind, I may use the single-sample mode

**Comment by melop** [comment]
You mentioned that you combined all samples into one bam file, are you doing it in a way that preserves the sample identity for each mapped read? Normally you supply a list of bam files (one for each sample) to bcftools call command, so that it knows where each read comes from. If you pool all reads together, the allele frequency becomes 0.001. This would appear as sequencing error and not called as variant, since bcftools assumes the data to come from a single diploid (by default) individual.

**Comment by ju-cheng** [comment]
Yes I kept the reads from different samples with their original read group.
So they are different

**Comment by sbslee** [comment]
Hi, thanks team for the awesome tool!

@pd3, do you happen to have any updates on:

> It is a known issue, the caller is tuned for common variation when run with many samples. I was planning to add a switch to act as a single-sample caller even in the presence of many samples, but never got around to doing it. Running in single-sample mode increases the number of false calls.

It'd be great if there were such switch so that users can control variant calling sensitivity in the presence of multiple samples (I have a robust variant filtering scheme ready down the road, so I'm OK with increased false positives). My variant of interest keeps disappearing when genotyped with other samples even though it correctly shows up in the mpileup output (i.e. likelihoods).

I confirmed that running each sample individually brings back the variant of interest as you suggested, but it would be appreciated if that can be handled at the program level.

**Comment by pd3** [comment]
Ah, this has been added a while ago, please check the `bcftools call --group-samples` option

*-G, --group-samples*
    by default, all samples are assumed to come from a single population. This option allows to group samples
    into populations and apply the HWE assumption within but not across the populations. 'FILE' is a tab-delimited
    text file with sample names in the first column and group names in the second column. If '-' is
    given instead, no HWE assumption is made at all and single-sample calling is performed. (Note that
    in low coverage data this inflates the rate of false positives.) The *-G* option requires the presence of
    per-sample FORMAT/QS or FORMAT/AD tag generated with *bcftools mpileup -a QS* (or *-a AD*).
