### ISSUE TITLE
chr20 to 20 contig ID conversion

### ISSUE THREAD

**Issue by winni2k** [samtools/bcftools#83]
Is there an easy way in bcftools to convert contig ID names in an indexed bcf? I would prefer not to have to convert to VCF and use something like <code>sed 's/^chr//'</code> to do the job.

**Comment by tommycarstensen** [comment]
Has `bcftools annotate --rename-chrs` been added to the main branch? I just did a git pull and recompiled and got `reheader: unrecognized option '--rename-chrs'`. Thanks!

**Comment by pd3** [comment]
I think you probably run `bcftools reheader --rename-chrs` instead of `bcftools annotate --rename-chrs`?

**Comment by tommycarstensen** [comment]
@pd3 I'm an idiot. Thanks Petr.

P.S. I went for `awk` in the end. That vcf file needed a lot of polishing.

**Comment by jkbonfield** [comment]
This raises an issue of the VCF spec though.

For SAM we added SQ line "AN" fields for alternative name.  The ID used in the file is the primary name, but it permits eg `@SQ SN:20 AN:chr20 LN:63025520 ...` to be specified, permitting applications to then accept 20 or chr20 in region specifiers (I don't think samtools does this yet though).

Such a mechanism doesn't exist in VCF sadly.  Should it?  Maybe we'd need something equivalent for the contig lines, eg `##contig=<ID=20,AN=chr20;Chr20,length=63025520,...>`.  I'm not sure semicolon is great, but it's either that or repeated AN keys and hope people can implement a hash table mechanism that appends instead of overwrites.

Thoughts?

**Comment by jmarshall** [comment]
Samtools indeed doesn't implement \@SQ-AN yet; there are some htsjdk/picard PRs for it that may or may not have been merged.

You are right — once AN in SAM becomes usable in the tools, it would be good to be able to transmit the aliases to VCF files.  Perhaps it could use a quoted string to avoid the delimiter infelicity:

    ##contig=<ID=20,alternativeID="chr20,Chr20",length=63025520,...>

**Comment by jkbonfield** [comment]
Quotes are better.  I'm a VCF newbie so wasn't sure what was viable in the syntax.
