### ISSUE TITLE
some questions on new SNP calling pipeline 

### ISSUE THREAD

**Issue by Jolvii85** [samtools/bcftools#849]
Hi,

I am trying to use bcftools v1.9 to do SNP calling, while I have some question as following:
1)  how to add  "DP,AD,ADF,ADR,SP,INFO/AD,INFO/ADF,INFO/ADR" flag in bcftools mpileup & bcftools call pipeline (former -t parameter in samtools mpileup)?
2) how to call SNPs for specific region (former -l parameter in samtool smpileup )? 
3) it seems like samtools and bcftools pipeline (v1.7) would get much less SNPs than GATK pipeline (after same filtering criterion), i.e. samtools does not call some SNPs even it is there, do you know why?
Thank you for your time.

Best regards

**Comment by pd3** [comment]
The `samtools mpileup -t` option was replaced with `bcftools mpileup --annotate` option, in order to make the `-t` consistent with the rest of `bcftools`.

To specify the region, check the `-r, --regions` option. The full documentation can be found here http://samtools.github.io/bcftools/bcftools.html and some examples here http://samtools.github.io/bcftools/howtos/.

Both programs use different calling algorithms and there are number of options one can tweak to influence the results. For example one can set different quality thresholds, turn off realignment, increase or decrease the sensitivity by modifying the prior.

**Comment by Jolvii85** [comment]
Hi, 
If I using -R parameter, can I feed the same bed file to specify the region I want to do SNP calling?
Thank you!

**Comment by pd3** [comment]
yes, as described in the documentation http://samtools.github.io/bcftools/bcftools-man.html#common_options

**Comment by pd3** [comment]
How many input files do you have? Keeping indexes to multiple files increases the memory requirements. If this were the problem, using `-T` instead to stream through the whole BAM instead of index-jumping should help.

**Comment by Jolvii85** [comment]
Yes, U are right, the T parameters can save a lot of memory.

**Comment by Jolvii85** [comment]
Thank you.

**Comment by pd3** [comment]
This issue seems resolved, closing now.
