### ISSUE TITLE
When merging, remove SNPs that do not match the REF allele, without considering ALT alleles

### ISSUE THREAD

**Issue by MrLocuace** [samtools/bcftools#879]
Hello, I have vcf files from 2 populations which I want to merge. In the REF and ALT columns I have situations like this one:

pop1:

    ID   REF    ALT
    rs1    A    C
    rs2    C    .

pop2:

ID   REF    ALT
rs1    C   A
rs2    C   T

I want to remove SNPs that do not match the REF allele, but not to remove SNPs where the mismatch is due to "." in ALT. How to do it with bcftools?. Thank you !

**Comment by MrLocuace** [comment]
Hi @finswimmer, thank you for your reply. No, besides biallelic SNPs, I am also interested in SNPs that are monoallelic in one population but biallelic in the other. If I use bcftools with the option that removes SNPs that have REF and ALT alleles flipped between the populations, I will lose the monoallelic alleles.

**Comment by finswimmer** [comment]
Hello again,

I guess I don't understand what your goal is. So for clarification, could you please post some complete lines of your `vcf` files and show how your desired output for this example should look like?

fin swimmer

**Comment by MrLocuace** [comment]
Hi @finswimmer. I hope now I more clear:

pop1:

    #CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	pop1_1	pop1_2		
    10	273344	rs2448378	A	C	.	PASS	AR2=1;DR2=1;AF=0.069	GT	0|0	0|0	
    10	274224	rs2448377	A	G	.	PASS	AR2=1;DR2=1;AF=0.974	GT	1|1	1|1	
    10      333333  rs1       C      A   	.	PASS	AR2=1;DR2=19	GT	1|1	0|1	

pop2:

    #CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	pop2_1	pop2_2
    10	273344	rs2448378	A	.	.	PASS	AR2=0;DR2=0	GT	0|0	0|0	
    10	274224	rs2448377	A	G	.	PASS	AR2=1;DR2=1;AF=0.859	GT	1|1	0|1	
    10      333333  rs1        A      C   	.	PASS	AR2=1;DR2=19	GT	1|1	0|1	

merged pop1 and pop2:

    #CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	pop1_1	pop1_2	pop2_1	pop2_2	
    10	273344	rs2448378	A	C	.	PASS	AR2=1;DR2=1;AF=0.069	GT	0|0	0|0	0|0	0|0   
    10	274224	rs2448377	A	G	.	PASS	AR2=1;DR2=1;AF=0.974	GT	1|1	1|1	1|1	0|1
	
When merging, rs1 was removed due to flipped REF and ALT alleles between pop1 and pop2. Even though rs2448378 has ALT "C" in pop1 and "." in pop2, it was not removed, because this SNP is monoalleleic (fixed) in pop2 but biallelic in pop1. None of the bcftools -collapse options seem to be suitable for this task. Thank you !

**Comment by finswimmer** [comment]
Hello again,

now I understood better. 

In my testing `bcftools merge` merges lines where CHROM, POS, REF are  identical but the ALT is missing in one of the files.

For your second request, to remove lines where there is a mismatch of the REF between the files, I have no solution. It might be possible that the maintainer include in option to skip lines with an error instead of stopping. But it doesn't feel clean.

I guess your post here is connected to the one on [biostars](https://www.biostars.org/p/336399)? I would suggest to go on discussing what's your goal ,on biostars, as the issue tracker on github is more meant for bug r eports, feature requests or clarifications.

fin swimmer

**Comment by MrLocuace** [comment]
Thank you @finswimmer !
