### ISSUE TITLE
bcftools error reporting is terrible

### ISSUE THREAD

**Issue by golharam** [samtools/bcftools#925]
Better error reporting is needed other than "Could not load index" when running various commands.  Turn out it was first because my vcf files were not compressed, then not index, then the chromosome names didn't match, then it was because my open file limit was too low.   Figuring this out would have been much easier with decent error messages.

**Comment by pd3** [comment]
Compressed and indexed files are a prerequisite to most bcftools commands, this is described in the man page http://samtools.github.io/bcftools/bcftools.html.

Otherwise yes, you are right, error reporting could be certainly improved. Unfortunately, your feedback is not that great either. Better user reporting is needed other than "when I run various commands things don't go well". Consider reporting the exact commands that cause the trouble, version of the software and steps to reproduce.

**Comment by zhpn1024** [comment]
Couldn't agree more.

**Comment by pd3** [comment]
A slight improvement to this has been just pushed via be4494b. However, the main message remains the same and it is up to the user to make the deduction that `bcftools index` must be run in order to index the file. For the rest of the complaints, a more detailed and reproducible report would be needed.
