### ISSUE TITLE
feature request: consensus

### ISSUE THREAD

**Issue by jullee** [samtools/bcftools#940]
Forgive me if I've missed a way to do this. Otherwise, it would be so great if when using the consensus command there was a way to insert "N" instead of the reference base for sites that are not included in the vcf produced by mpileup > call. We can't be sure those sites are reference bases. It would be better if they were listed as missing. 

It looks like the only way to currently achieve this is to mask missing sites in the reference and that's a bunch of extra steps (i.e. places where I can go wrong!)

**Comment by jbruxaux** [comment]
I agree with this request!

It would be really nice to have this option, or at list to mention that a missing site in the vcf is by default considered as the ref allele, which can be really misleading when dealing with low coverage and missing data. I realized it was the case only because all my consensus sequences with missing data clustered together...

Another option could be to include all the positions in the output file of the mpileup command (currently only positions with depth 1 or more are included).

**Comment by pd3** [comment]
This is now addressed by a new `-a, --absent` option. Please try it out and let me know in case of problems.
