### ISSUE TITLE
Help understanding breakdown of SNP/indel calling workflow

### ISSUE THREAD

**Issue by jullee** [samtools/bcftools#945]
Not sure if this is the best place to ask questions about the usage of different tools. I'm still new at this and just want to make sure I understand the tools I'm using correctly. 

I'm hoping to use bcftools to call variants in mitochondrial genes relative to a reference. I'm using mpileup>call>filter>consensus. I *think* I know what is happening at each step based on the manual and various online forums but it would be great to have confirmation for some of the specific details at each step:

1) mpileup command
Following alignment, this command is just gathering all information available per site on read depth, quality etc. and calculating the likelihoods of different genotypes from what I understand.
When I specify "input options" at this stage and "options for SNP/indel genotype likelihood calculations", these affect a) whether a read/base is included in the summary info at all and b) whether a read/base is considered in the genotype likelihood scores? 

If I've set -Q 20 and I have ten reads at a site but only 7 have base quality >20 at that site, then my mpileup INFO/DP output for that site will be 7? or will it be 10 and the quality issues be reflected in one of the other INFO fields?

If I likewise set -m 10 but only have 7 reads aligning to that region (gapped or otherwise), then the mpileup output will not indicate that possibility of an indel at that site in the ATL column? Same if I have 20 reads aligning to that region but only 7 are gapped? In these cases, will the ALT column be "blank"?  Or does a possible indel get recorded in the ALT field and this parameter setting only affect the genotype likelihood scores?

2) call command
If I understand this next step correctly, this step is taking the mpileup genotype likelihoods and now calling the genotype per site (picking the one with the highest likelihood). So my vcf output here is showing me the final genotype call and its phred-scaled likelihood. For mtDNA I've set ploidy to 1 so it's effectively forced to make a homozygous REF or homozygous ALT call here? 

3) filter command
This is maybe the part where I'm  confused. Here, I go back through my calls and based on hard filters such as coverage, quality etc., assess whether my calls should "pass" or "fail". But is some of this redundant with the mpileup command? For instance if I set -Q 20 in my mpileup command, is it redundant to set "--include 'QUAL >=20' in this command? 

Thank you in advance for helping to clarify the details!

**Comment by pd3** [comment]
Your guesses are essentially correct. If you are interested in details, there are some math notes linked from this page http://samtools.github.io/bcftools.

1. yes, in the mpileup step, the pre-filtering removes reads from PL calculation. The INFO/DP tag displays the number of raw reads. If strict thresholds are applied and an indel is not considered for calling, and also no SNP is present, a site will appear as identical to reference.

2. the math is a bit more complicated than just picking the highest PL, it calculates posterior probabilities based on the PLs. Consult the math notes for details. By setting the ploidy to 1 only R or A genotypes are considered, instead of the default RR, RA, AA genotypes.

3. this point you got incorrectly. There are different qualities in play: mapping qualities of the reads (MQ in BAM), base qualities of the reads (string of BQs in BAM), variant call qualities (the QUAL column in VCF), genotype qualities (FORMAT/GQ in VCF). The expression `-i "QUAL>=20"` filters the QUAL column and is unrelated to the MQs or BQs.

I hope this helps.
