### ISSUE TITLE
Include more header lines to file

### ISSUE THREAD

**Issue by evofish** [samtools/bcftools#972]
Hello, I am having trouble adding to more information to my *.vcf file. The only thing that appears to be related to the issue is the "annotate" function, for which i ran:  

**bcftools annotate -h header-lines.txt snps-filtered.vcf**

However this exits with an error:  "Could not parse header lines"

The information that I would like to include for all samples in my *.VCF file are: Allele Depth and Genotype Likelihood.

Hence my Header file reads: 
 ##FORMAT=<ID=AD,Number=1,Type=Integer,Description="Allele Depth">
 ##FORMAT=<ID=GL,Number=1,Type=Integer,Description="Genotype Likelihood">

Any input would be greatly appreciated. Thanks in advance! 
****

**Comment by pd3** [comment]
Is it possible the lines in your header file have a leading space? The lines must start with the hash character `#`.

**Comment by evofish** [comment]
Thanks for the reply, this didn't work. 

The only thing I could think of was to go all the way back to the _bcftools mpileup_ command, an include _**-a "AD,PL"**_ This provided me with the necessary information on the VCF file.

**Comment by pd3** [comment]
The two lines you show above worked for me after the leading space is removed, therefore I suspect the problem is white-space characters messing up the header lines. (You can always use `bcftools view -h file.vcf > header.txt` to create a template with valid header lines and edit it to prevent problems like this.)

If you think this is a problem with bcftools and not with `header-lines.txt`, we'd need a copy of the file for debugging. I take the problem is resolved now.
