### ISSUE TITLE
Negative record numbers in bcftools stats output 

### ISSUE THREAD

**Issue by sahwa** [samtools/bcftools#978]
I've noticed that under in the file `vcfstats.c`, the variable `n_records` is declared as an `int`:

```
typedef struct
{
    int n_snps, n_indels, n_mnps, n_others, n_mals, n_snp_mals, n_records, n_noalts;
```

, which means that the maximum value it can take is 2,147,483,647, and any value above this will return a nonsense value when it is printed. Thus, when you have a file which holds non-variable entries, such as whole genome data, and the number of positions is more than 2,147,483,647, the output of `bcftools stats my.vcf.gz` will be incorrect. 

Example:

Where total number of entries is less than 2,147,483,647. Correct number of positions.

```
# SN    [2]id   [3]key  [4]value
SN      0       number of samples:      1
SN      0       number of records:      2054488017
SN      0       number of no-ALTs:      2025765910
SN      0       number of SNPs: 28722107
SN      0       number of MNPs: 0
SN      0       number of indels:       0
SN      0       number of others:       0
SN      0       number of multiallelic sites:   16564
SN      0       number of multiallelic SNP sites:       16564
```

Where total number of entries is more than 2,147,483,647. Incorrect number of positions.

```
# SN    [2]id   [3]key  [4]value
SN      0       number of samples:      1
SN      0       number of records:      -1562896920
SN      0       number of no-ALTs:      -1581570022
SN      0       number of SNPs: 18673102
SN      0       number of MNPs: 0
SN      0       number of indels:       0
SN      0       number of others:       0
SN      0       number of multiallelic sites:   14222
SN      0       number of multiallelic SNP sites:       14222
```

Maybe request storing the value `n_records` as a `long unsigned int`, rather than just an `int`?

**Comment by pd3** [comment]
This is caused by an integer overflow. I guess you are working with a large, non-human, genome? It should be fixed now. Thanks for the report.

**Comment by alanrogers** [comment]
Can you tell me in which version of bcftools this problem was fixed? The latest version on our server is 1.12-89-g186dc93, and it exhibits this bug.

I'm running into this problem with human data from the Simons Genome Diversity Project. Those data include monomorphic sites as well as polymorphic ones, and the number of sites is too large to be represented by a 32-bit signed integer. The largest such integer is 2147483647, which is substantially smaller than the number of bases in a human genome.

**Comment by pd3** [comment]
Since version 1.10 this is represented as an unsigned 32-bit integer. The maximum number is 4,294,967,295 records which should be sufficient for human genome, unless there are many sites with duplicate coordinates. I can imagine that could happen with multiallelics split into biallelic records or with many indels.

So it seems we'll need to increase to 64-bit integers. Is it just these two values that overflowed for you or were there any others?

**Comment by pd3** [comment]
Hopefully this should fix it https://github.com/samtools/bcftools/commit/246c7edd9801f30b68b30be0acf3df1c776e0cc7

**Comment by alanrogers** [comment]
Thanks for the quick response. I have one minor suggestion for your format
strings: I think "PRId64" should be "PRIu64", because these are unsigned
ints.

In my own data, the number of positions was too large for int32_t, but not
too large for uint32_t. I suspect your printf statement was using %d rather
than %u to print values of type uint32_t. That would explain why I got a
negative integer in the output.
