### ISSUE TITLE
Get Dosages 'DS'

### ISSUE THREAD

**Issue by nunonog** [samtools/bcftools#989]
Hello,
I was trying to use bcftools to extract dosages using the tag 'DS' to get the dosages probabilities. 

I understood this feature is not implemented (?)
from the manual page:
"dosage
print genotype dosage. By default the plugin searches for PL, GL and GT, in that order."

When I do:
bcftools/bcftools  +dosage myVCF.vcf.gz -- -t DP
>No handler for tag "GP"

Am I correct - and if so is there a recommend alternative?

Thanks in advance
very best,
Nuno

**Comment by pd3** [comment]
Is the tag `DS` present in the VCF? You can verify by taking a look in the file with eg. `bcftools view myVCF.vcf.gz | less`. If not, the program cannot extract it.

The plugin `+dosage` calculates the values on the fly and can do so from one of the PL, GL or GT tags, as described in the documentation. It does not and cannot work with `DP` as in your example. I take it was a typo though, because the error message you provided says `GP`. GPs could be supported in principle, but someone would have to contribute a pull request. I am surprised your VCF does not have any of the supported tags, they are much more common in the VCF world than `GP`.

**Comment by nunonog** [comment]
Hi , thanks for your reply.

I was not very clear, apologies (indeed a typo). 

I do have the DS tag on my vcf:
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=DS,Number=1,Type=Float,Description="Estimated Alternate Allele Dosage : [P(0/1)+2*P(1/1)]">
##FORMAT=<ID=GP,Number=3,Type=Float,Description="Estimated Posterior Probabilities for Genotypes 0/0, 0/1 and 1/1">


My command works for the examples given in the documentation, either
bcftools  +dosage myvcf.vcf.gz -- -t PL
bcftools  +dosage myvcf.vcf.gz -- -t GL
bcftools  +dosage myvcf.vcf.gz -- -t GT

However, I would expect to work also with the 'DS' tag, and that is what is failing:
>
No handler for tag "DS"

I wanted to extract the Alternate Allele Dosage (tag DS)

Is this feature present ?


Thanks again
Nuno

**Comment by pd3** [comment]
Check this command http://samtools.github.io/bcftools/howtos/query.html

**Comment by nunonog** [comment]
Yes that works for what I wanted. I see this is rather obvious now... ( for some reason I just didn't think of using 'query' for this....)

Thanks again, great help

Nuno
